camel.rest-openapi.specificationPath=classpath:openapi/party632Individual.json

quarkus.log.level=TRACE
quarkus.log.category."org.apache.camel.quarkus".level=TRACE
quarkus.log.category."org.apache.camel".level=TRACE
javax.net.debug=ssl
quarkus.log.category."org.apache.camel.component.http"=TRACE


quarkus.jackson.serialization-inclusion=NON_NULL
quarkus.jackson.fail-on-unknown-properties=false



external.api.billing.party-url=https://172.27.108.62:8186/trerest_in/api/v1/individual
external.api.billing.customer-url=https://172.27.108.62:8186/trerest_in/api/v1/customer
external.api.billing.auth=Basic VFJFUkVTVDpXb3JrRm9yQWlydGVsJDEyMzQ=
# For HTTP component
#camel.component.http.connect-timeout=5000
#camel.component.http.responseTimeout=5000








