external.api.billing.party-url=https://172.27.108.62:8186/trerest_in/api/v1/individual
external.api.billing.customer-url=https://172.27.108.62:8186/trerest_in/api/v1/customer
external.api.billing.auth=Basic VFJFUkVTVDpXb3JrRm9yQWlydGVsJDEyMzQ=

