config_ordinal=500
external.api.billing.party-url=https://singleviewapi.i.airtel.ug:8165/trerest_in/api/v1/individual
external.api.billing.customer-url=https://singleviewapi.i.airtel.ug:8165/trerest_in/api/v1/customer
external.api.billing.customer-account-url=https://singleviewapi.i.airtel.ug:8165/trerest_in/api/v1/customerByAccountName
external.api.billing.auth=Basic VFJFUkVTVDpXb3JrRm9yQWlydGVsJDEyMzQ=