/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.Objects;
/**
 * Customer primary account or prepaid account for BalanceTransfer reason.
 */
@Schema(description = "Customer primary account or prepaid account for BalanceTransfer reason.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class AccountRef {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("accountNumber")
  private String accountNumber = null;

  @JsonProperty("accountBalance")
  private String accountBalance = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("accountType")
  private String accountType = null;

  @JsonProperty("creditLimit")
  private String creditLimit = null;

  @JsonProperty("availableCredit")
  private String availableCredit = null;

  @JsonProperty("billStructure")
  private BillStructure billStructure = null;

  @JsonProperty("paymentPlan")
  private PaymentPlan paymentPlan = null;

  @JsonProperty("dunningCase")
  private DunningCase dunningCase = null;

  public AccountRef id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Primary account id or prepaid account id, SV_MAPPING:Cust_Acct.PrimaryAcctID_I or Account.AcctID_I
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Primary account id or prepaid account id, SV_MAPPING:Cust_Acct.PrimaryAcctID_I or Account.AcctID_I")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AccountRef accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Primary account number or prepaid account number, SV_MAPPING:Cust_Acct.PrimaryAcctNum_X or Account.Name
   * @return accountNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Primary account number or prepaid account number, SV_MAPPING:Cust_Acct.PrimaryAcctNum_X or Account.Name")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public AccountRef accountBalance(String accountBalance) {
    this.accountBalance = accountBalance;
    return this;
  }

   /**
   * ACCOUNT_BALANCE, SV_MAPPING:Cust_Acct.PrimAcctBal_C or Account.AcctBalance_C
   * @return accountBalance
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "ACCOUNT_BALANCE, SV_MAPPING:Cust_Acct.PrimAcctBal_C or Account.AcctBalance_C")
  public String getAccountBalance() {
    return accountBalance;
  }

  public void setAccountBalance(String accountBalance) {
    this.accountBalance = accountBalance;
  }

  public AccountRef href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Reference of the account - &lt;http://&lt;TREREST_HOSTNAME&gt;:&lt;TREREST_PORT&gt;/&lt;Account TreREST URL&gt;/&lt;SV_MAPPING:Cust_Acct.PrimaryAcctNum_X&gt;. Not implemented yet.
   * @return href
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Reference of the account - <http://<TREREST_HOSTNAME>:<TREREST_PORT>/<Account TreREST URL>/<SV_MAPPING:Cust_Acct.PrimaryAcctNum_X>. Not implemented yet.")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public AccountRef accountType(String accountType) {
    this.accountType = accountType;
    return this;
  }

   /**
   * Account type, SV_MAPPING:Account.Type_R
   * @return accountType
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Account type, SV_MAPPING:Account.Type_R")
  public String getAccountType() {
    return accountType;
  }

  public void setAccountType(String accountType) {
    this.accountType = accountType;
  }

  public AccountRef creditLimit(String creditLimit) {
    this.creditLimit = creditLimit;
    return this;
  }

   /**
   * Credit Limit, SV_MAPPING:Account.CreditLimit_C
   * @return creditLimit
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit Limit, SV_MAPPING:Account.CreditLimit_C")
  public String getCreditLimit() {
    return creditLimit;
  }

  public void setCreditLimit(String creditLimit) {
    this.creditLimit = creditLimit;
  }

  public AccountRef availableCredit(String availableCredit) {
    this.availableCredit = availableCredit;
    return this;
  }

   /**
   * AVAILABLE_CREDIT, SV_MAPPING:Account.AvailableCredit_C
   * @return availableCredit
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "AVAILABLE_CREDIT, SV_MAPPING:Account.AvailableCredit_C")
  public String getAvailableCredit() {
    return availableCredit;
  }

  public void setAvailableCredit(String availableCredit) {
    this.availableCredit = availableCredit;
  }

  public AccountRef billStructure(BillStructure billStructure) {
    this.billStructure = billStructure;
    return this;
  }

   /**
   * Get billStructure
   * @return billStructure
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public BillStructure getBillStructure() {
    return billStructure;
  }

  public void setBillStructure(BillStructure billStructure) {
    this.billStructure = billStructure;
  }

  public AccountRef paymentPlan(PaymentPlan paymentPlan) {
    this.paymentPlan = paymentPlan;
    return this;
  }

   /**
   * Get paymentPlan
   * @return paymentPlan
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public PaymentPlan getPaymentPlan() {
    return paymentPlan;
  }

  public void setPaymentPlan(PaymentPlan paymentPlan) {
    this.paymentPlan = paymentPlan;
  }

  public AccountRef dunningCase(DunningCase dunningCase) {
    this.dunningCase = dunningCase;
    return this;
  }

   /**
   * Get dunningCase
   * @return dunningCase
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public DunningCase getDunningCase() {
    return dunningCase;
  }

  public void setDunningCase(DunningCase dunningCase) {
    this.dunningCase = dunningCase;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountRef accountRef = (AccountRef) o;
    return Objects.equals(this.id, accountRef.id) &&
        Objects.equals(this.accountNumber, accountRef.accountNumber) &&
        Objects.equals(this.accountBalance, accountRef.accountBalance) &&
        Objects.equals(this.href, accountRef.href) &&
        Objects.equals(this.accountType, accountRef.accountType) &&
        Objects.equals(this.creditLimit, accountRef.creditLimit) &&
        Objects.equals(this.availableCredit, accountRef.availableCredit) &&
        Objects.equals(this.billStructure, accountRef.billStructure) &&
        Objects.equals(this.paymentPlan, accountRef.paymentPlan) &&
        Objects.equals(this.dunningCase, accountRef.dunningCase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountNumber, accountBalance, href, accountType, creditLimit, availableCredit, billStructure, paymentPlan, dunningCase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountRef {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    accountBalance: ").append(toIndentedString(accountBalance)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    accountType: ").append(toIndentedString(accountType)).append("\n");
    sb.append("    creditLimit: ").append(toIndentedString(creditLimit)).append("\n");
    sb.append("    availableCredit: ").append(toIndentedString(availableCredit)).append("\n");
    sb.append("    billStructure: ").append(toIndentedString(billStructure)).append("\n");
    sb.append("    paymentPlan: ").append(toIndentedString(paymentPlan)).append("\n");
    sb.append("    dunningCase: ").append(toIndentedString(dunningCase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
