/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.Date;
import java.util.Objects;
/**
 * Details of a bank card
 */
@Schema(description = "Details of a bank card")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class BankCardType {
  @JsonProperty("brand")
  private String brand = null;

  @JsonProperty("cardNumber")
  private String cardNumber = null;

  @JsonProperty("expirationDate")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
  private Date expirationDate = null;

  @JsonProperty("nameOnCard")
  private String nameOnCard = null;

  @JsonProperty("cvv")
  private String cvv = null;

  @JsonProperty("status")
  private String status = null;

  public BankCardType brand(String brand) {
    this.brand = brand;
    return this;
  }

   /**
   * Brand Name, SV_MAPPING:Cust_Acct.CreditCardCompany_R
   * @return brand
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Brand Name, SV_MAPPING:Cust_Acct.CreditCardCompany_R")
  public String getBrand() {
    return brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public BankCardType cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * Credit Card number, SV_MAPPING:Cust_Acct.CreditCardNumber_X
   * @return cardNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit Card number, SV_MAPPING:Cust_Acct.CreditCardNumber_X")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public BankCardType expirationDate(Date expirationDate) {
    this.expirationDate = expirationDate;
    return this;
  }

   /**
   * Credit Card expiry date, SV_MAPPING:Cust_Acct.CreditCardExpiry_X
   * @return expirationDate
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit Card expiry date, SV_MAPPING:Cust_Acct.CreditCardExpiry_X")
  public Date getExpirationDate() {
    return expirationDate;
  }

  public void setExpirationDate(Date expirationDate) {
    this.expirationDate = expirationDate;
  }

  public BankCardType nameOnCard(String nameOnCard) {
    this.nameOnCard = nameOnCard;
    return this;
  }

   /**
   * Name on the credit card, SV_MAPPING:Cust_Acct.CreditCardName_X
   * @return nameOnCard
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Name on the credit card, SV_MAPPING:Cust_Acct.CreditCardName_X")
  public String getNameOnCard() {
    return nameOnCard;
  }

  public void setNameOnCard(String nameOnCard) {
    this.nameOnCard = nameOnCard;
  }

  public BankCardType cvv(String cvv) {
    this.cvv = cvv;
    return this;
  }

   /**
   * Name on the credit card, SV_MAPPING:Cust_Acct.CreditCardSecurity_X
   * @return cvv
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Name on the credit card, SV_MAPPING:Cust_Acct.CreditCardSecurity_X")
  public String getCvv() {
    return cvv;
  }

  public void setCvv(String cvv) {
    this.cvv = cvv;
  }

  public BankCardType status(String status) {
    this.status = status;
    return this;
  }

   /**
   * CARD_STATUS_CODE, SV_MAPPING:Cust_Acct.CreditCardStatus_R
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "CARD_STATUS_CODE, SV_MAPPING:Cust_Acct.CreditCardStatus_R")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankCardType bankCardType = (BankCardType) o;
    return Objects.equals(this.brand, bankCardType.brand) &&
        Objects.equals(this.cardNumber, bankCardType.cardNumber) &&
        Objects.equals(this.expirationDate, bankCardType.expirationDate) &&
        Objects.equals(this.nameOnCard, bankCardType.nameOnCard) &&
        Objects.equals(this.cvv, bankCardType.cvv) &&
        Objects.equals(this.status, bankCardType.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(brand, cardNumber, expirationDate, nameOnCard, cvv, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankCardType {\n");
    
    sb.append("    brand: ").append(toIndentedString(brand)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    expirationDate: ").append(toIndentedString(expirationDate)).append("\n");
    sb.append("    nameOnCard: ").append(toIndentedString(nameOnCard)).append("\n");
    sb.append("    cvv: ").append(toIndentedString(cvv)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
