/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Details of a bank account
 */
@Schema(description = "Details of a bank account")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class BankAccountDebitType {
  @JsonProperty("accountNumber")
  private String accountNumber = null;

  @JsonProperty("BIC")
  private String BIC = null;

  @JsonProperty("owner")
  private String owner = null;

  @JsonProperty("paymentLimit")
  private String paymentLimit = null;

  @JsonProperty("status")
  private String status = null;

  public BankAccountDebitType accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }

   /**
   * Account number, SV_MAPPING:Cust_Acct.BankAcctNum_X
   * @return accountNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Account number, SV_MAPPING:Cust_Acct.BankAcctNum_X")
  public String getAccountNumber() {
    return accountNumber;
  }

  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public BankAccountDebitType BIC(String BIC) {
    this.BIC = BIC;
    return this;
  }

   /**
   * BIC, SV_MAPPING:Cust_Acct.Bank_R
   * @return BIC
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "BIC, SV_MAPPING:Cust_Acct.Bank_R")
  public String getBIC() {
    return BIC;
  }

  public void setBIC(String BIC) {
    this.BIC = BIC;
  }

  public BankAccountDebitType owner(String owner) {
    this.owner = owner;
    return this;
  }

   /**
   * Owner, SV_MAPPING:Cust_Acct.BankAcctName_X
   * @return owner
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Owner, SV_MAPPING:Cust_Acct.BankAcctName_X")
  public String getOwner() {
    return owner;
  }

  public void setOwner(String owner) {
    this.owner = owner;
  }

  public BankAccountDebitType paymentLimit(String paymentLimit) {
    this.paymentLimit = paymentLimit;
    return this;
  }

   /**
   * Payment limit, SV_MAPPING:Cust_Acct.BankAcctReference_X
   * @return paymentLimit
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Payment limit, SV_MAPPING:Cust_Acct.BankAcctReference_X")
  public String getPaymentLimit() {
    return paymentLimit;
  }

  public void setPaymentLimit(String paymentLimit) {
    this.paymentLimit = paymentLimit;
  }

  public BankAccountDebitType status(String status) {
    this.status = status;
    return this;
  }

   /**
   * BANK_ACCOUNT_STATUS_CODE, SV_MAPPING:Cust_Acct.BankAcctStatus_R
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "BANK_ACCOUNT_STATUS_CODE, SV_MAPPING:Cust_Acct.BankAcctStatus_R")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BankAccountDebitType bankAccountDebitType = (BankAccountDebitType) o;
    return Objects.equals(this.accountNumber, bankAccountDebitType.accountNumber) &&
        Objects.equals(this.BIC, bankAccountDebitType.BIC) &&
        Objects.equals(this.owner, bankAccountDebitType.owner) &&
        Objects.equals(this.paymentLimit, bankAccountDebitType.paymentLimit) &&
        Objects.equals(this.status, bankAccountDebitType.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountNumber, BIC, owner, paymentLimit, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BankAccountDebitType {\n");
    
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("    BIC: ").append(toIndentedString(BIC)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    paymentLimit: ").append(toIndentedString(paymentLimit)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
