/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * The bill structure that associated to the customer.
 */
@Schema(description = "The bill structure that associated to the customer.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class BillStructure {
  @JsonProperty("cycleSpecification")
  private CycleSpecification cycleSpecification = null;

  @JsonProperty("format")
  private List<Format> format = null;

  public BillStructure cycleSpecification(CycleSpecification cycleSpecification) {
    this.cycleSpecification = cycleSpecification;
    return this;
  }

   /**
   * Get cycleSpecification
   * @return cycleSpecification
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public CycleSpecification getCycleSpecification() {
    return cycleSpecification;
  }

  public void setCycleSpecification(CycleSpecification cycleSpecification) {
    this.cycleSpecification = cycleSpecification;
  }

  public BillStructure format(List<Format> format) {
    this.format = format;
    return this;
  }

  public BillStructure addFormatItem(Format formatItem) {
    if (this.format == null) {
      this.format = new ArrayList<Format>();
    }
    this.format.add(formatItem);
    return this;
  }

   /**
   * The bill invoice format.
   * @return format
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The bill invoice format.")
  public List<Format> getFormat() {
    return format;
  }

  public void setFormat(List<Format> format) {
    this.format = format;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BillStructure billStructure = (BillStructure) o;
    return Objects.equals(this.cycleSpecification, billStructure.cycleSpecification) &&
        Objects.equals(this.format, billStructure.format);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cycleSpecification, format);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BillStructure {\n");
    
    sb.append("    cycleSpecification: ").append(toIndentedString(cycleSpecification)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
