/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Credit profile for the party.
 */
@Schema(description = "Credit profile for the party.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class CreditProfile {
  @JsonProperty("creditRiskRating")
  private String creditRiskRating = null;

  @JsonProperty("creditLimit")
  private String creditLimit = null;

  @JsonProperty("creditLimitCurrency")
  private String creditLimitCurrency = null;

  @JsonProperty("expectedRevenue")
  private String expectedRevenue = null;

  @JsonProperty("expRevCurrency")
  private String expRevCurrency = null;

  @JsonProperty("creditComments")
  private String creditComments = null;

  @JsonProperty("taxClass")
  private String taxClass = null;

  @JsonProperty("creditScore")
  private String creditScore = null;

  public CreditProfile creditRiskRating(String creditRiskRating) {
    this.creditRiskRating = creditRiskRating;
    return this;
  }

   /**
   * Credit rating, SV_MAPPING:Cust_Acct.CreditRating_R
   * @return creditRiskRating
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit rating, SV_MAPPING:Cust_Acct.CreditRating_R")
  public String getCreditRiskRating() {
    return creditRiskRating;
  }

  public void setCreditRiskRating(String creditRiskRating) {
    this.creditRiskRating = creditRiskRating;
  }

  public CreditProfile creditLimit(String creditLimit) {
    this.creditLimit = creditLimit;
    return this;
  }

   /**
   * CREDIT_LIMIT, SV_MAPPING:Cust_Acct.CreditLimit_C
   * @return creditLimit
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "CREDIT_LIMIT, SV_MAPPING:Cust_Acct.CreditLimit_C")
  public String getCreditLimit() {
    return creditLimit;
  }

  public void setCreditLimit(String creditLimit) {
    this.creditLimit = creditLimit;
  }

  public CreditProfile creditLimitCurrency(String creditLimitCurrency) {
    this.creditLimitCurrency = creditLimitCurrency;
    return this;
  }

   /**
   * Credit limit Currency, SV_MAPPING:Cust_Acct.CreditLimitCurrency_R
   * @return creditLimitCurrency
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit limit Currency, SV_MAPPING:Cust_Acct.CreditLimitCurrency_R")
  public String getCreditLimitCurrency() {
    return creditLimitCurrency;
  }

  public void setCreditLimitCurrency(String creditLimitCurrency) {
    this.creditLimitCurrency = creditLimitCurrency;
  }

  public CreditProfile expectedRevenue(String expectedRevenue) {
    this.expectedRevenue = expectedRevenue;
    return this;
  }

   /**
   * Expected revenue, SV_MAPPING:Cust_Acct.ExptRevAmt_C
   * @return expectedRevenue
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Expected revenue, SV_MAPPING:Cust_Acct.ExptRevAmt_C")
  public String getExpectedRevenue() {
    return expectedRevenue;
  }

  public void setExpectedRevenue(String expectedRevenue) {
    this.expectedRevenue = expectedRevenue;
  }

  public CreditProfile expRevCurrency(String expRevCurrency) {
    this.expRevCurrency = expRevCurrency;
    return this;
  }

   /**
   * Expected revenue currency, SV_MAPPING:Cust_Acct.ExptRevCurrency_R
   * @return expRevCurrency
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Expected revenue currency, SV_MAPPING:Cust_Acct.ExptRevCurrency_R")
  public String getExpRevCurrency() {
    return expRevCurrency;
  }

  public void setExpRevCurrency(String expRevCurrency) {
    this.expRevCurrency = expRevCurrency;
  }

  public CreditProfile creditComments(String creditComments) {
    this.creditComments = creditComments;
    return this;
  }

   /**
   * Credit comments, SV_MAPPING:Cust_Acct.CreditComments_X
   * @return creditComments
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit comments, SV_MAPPING:Cust_Acct.CreditComments_X")
  public String getCreditComments() {
    return creditComments;
  }

  public void setCreditComments(String creditComments) {
    this.creditComments = creditComments;
  }

  public CreditProfile taxClass(String taxClass) {
    this.taxClass = taxClass;
    return this;
  }

   /**
   * Tax class, SV_MAPPING:Cust_Acct.TaxClass_R
   * @return taxClass
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Tax class, SV_MAPPING:Cust_Acct.TaxClass_R")
  public String getTaxClass() {
    return taxClass;
  }

  public void setTaxClass(String taxClass) {
    this.taxClass = taxClass;
  }

  public CreditProfile creditScore(String creditScore) {
    this.creditScore = creditScore;
    return this;
  }

   /**
   * Credit score, SV_MAPPING:Cust_Acct.CreditScore_X
   * @return creditScore
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Credit score, SV_MAPPING:Cust_Acct.CreditScore_X")
  public String getCreditScore() {
    return creditScore;
  }

  public void setCreditScore(String creditScore) {
    this.creditScore = creditScore;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditProfile creditProfile = (CreditProfile) o;
    return Objects.equals(this.creditRiskRating, creditProfile.creditRiskRating) &&
        Objects.equals(this.creditLimit, creditProfile.creditLimit) &&
        Objects.equals(this.creditLimitCurrency, creditProfile.creditLimitCurrency) &&
        Objects.equals(this.expectedRevenue, creditProfile.expectedRevenue) &&
        Objects.equals(this.expRevCurrency, creditProfile.expRevCurrency) &&
        Objects.equals(this.creditComments, creditProfile.creditComments) &&
        Objects.equals(this.taxClass, creditProfile.taxClass) &&
        Objects.equals(this.creditScore, creditProfile.creditScore);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditRiskRating, creditLimit, creditLimitCurrency, expectedRevenue, expRevCurrency, creditComments, taxClass, creditScore);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditProfile {\n");
    
    sb.append("    creditRiskRating: ").append(toIndentedString(creditRiskRating)).append("\n");
    sb.append("    creditLimit: ").append(toIndentedString(creditLimit)).append("\n");
    sb.append("    creditLimitCurrency: ").append(toIndentedString(creditLimitCurrency)).append("\n");
    sb.append("    expectedRevenue: ").append(toIndentedString(expectedRevenue)).append("\n");
    sb.append("    expRevCurrency: ").append(toIndentedString(expRevCurrency)).append("\n");
    sb.append("    creditComments: ").append(toIndentedString(creditComments)).append("\n");
    sb.append("    taxClass: ").append(toIndentedString(taxClass)).append("\n");
    sb.append("    creditScore: ").append(toIndentedString(creditScore)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
