/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Customer List
 */
@Schema(description = "Customer List")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class CustomerList {
  @JsonProperty("allObjKeys")
  private List<Long> allObjKeys = null;

  @JsonProperty("totalObjects")
  private Long totalObjects = null;

  @JsonProperty("customers")
  private List<Customer> customers = null;

  @JsonProperty("warningMessage")
  private String warningMessage = null;

  public CustomerList allObjKeys(List<Long> allObjKeys) {
    this.allObjKeys = allObjKeys;
    return this;
  }

  public CustomerList addAllObjKeysItem(Long allObjKeysItem) {
    if (this.allObjKeys == null) {
      this.allObjKeys = new ArrayList<Long>();
    }
    this.allObjKeys.add(allObjKeysItem);
    return this;
  }

   /**
   * All object keys which met search criteria. This information is used for pagination.
   * @return allObjKeys
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "All object keys which met search criteria. This information is used for pagination.")
  public List<Long> getAllObjKeys() {
    return allObjKeys;
  }

  public void setAllObjKeys(List<Long> allObjKeys) {
    this.allObjKeys = allObjKeys;
  }

  public CustomerList totalObjects(Long totalObjects) {
    this.totalObjects = totalObjects;
    return this;
  }

   /**
   * Total number of items matching criteria
   * @return totalObjects
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Total number of items matching criteria")
  public Long getTotalObjects() {
    return totalObjects;
  }

  public void setTotalObjects(Long totalObjects) {
    this.totalObjects = totalObjects;
  }

  public CustomerList customers(List<Customer> customers) {
    this.customers = customers;
    return this;
  }

  public CustomerList addCustomersItem(Customer customersItem) {
    if (this.customers == null) {
      this.customers = new ArrayList<Customer>();
    }
    this.customers.add(customersItem);
    return this;
  }

   /**
   * Describes the list of customers with details
   * @return customers
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the list of customers with details")
  public List<Customer> getCustomers() {
    return customers;
  }

  public void setCustomers(List<Customer> customers) {
    this.customers = customers;
  }

  public CustomerList warningMessage(String warningMessage) {
    this.warningMessage = warningMessage;
    return this;
  }

   /**
   * Warning message details.
   * @return warningMessage
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Warning message details.")
  public String getWarningMessage() {
    return warningMessage;
  }

  public void setWarningMessage(String warningMessage) {
    this.warningMessage = warningMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerList customerList = (CustomerList) o;
    return Objects.equals(this.allObjKeys, customerList.allObjKeys) &&
        Objects.equals(this.totalObjects, customerList.totalObjects) &&
        Objects.equals(this.customers, customerList.customers) &&
        Objects.equals(this.warningMessage, customerList.warningMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allObjKeys, totalObjects, customers, warningMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerList {\n");
    
    sb.append("    allObjKeys: ").append(toIndentedString(allObjKeys)).append("\n");
    sb.append("    totalObjects: ").append(toIndentedString(totalObjects)).append("\n");
    sb.append("    customers: ").append(toIndentedString(customers)).append("\n");
    sb.append("    warningMessage: ").append(toIndentedString(warningMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
