/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Skipped properties: id, href
 */
@Schema(description = "Skipped properties: id, href")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class CustomerUpdate {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("statusChangeReason")
  private String statusChangeReason = null;

  @JsonProperty("validFor")
  private TimePeriod validFor = null;

  @JsonProperty("engagedParty")
  private List<PartyRef> engagedParty = null;

  @JsonProperty("characteristic")
  private List<Characteristic> characteristic = null;

  @JsonProperty("relatedParty")
  private List<PartyRef> relatedParty = null;

  @JsonProperty("account")
  private List<AccountRef> account = null;

  @JsonProperty("creditProfile")
  private CreditProfile creditProfile = null;

  @JsonProperty("paymentMethod")
  private List<PaymentMethodRef> paymentMethod = null;

  @JsonProperty("contactMedium")
  private List<ContactMedium> contactMedium = null;

  @JsonProperty("taxExemptionCertificate")
  private List<TaxExemptionCertificate> taxExemptionCertificate = null;

  @JsonProperty("treatmentExemption")
  private TreatmentExemption treatmentExemption = null;

  @JsonProperty("case")
  private CaseRef _case = null;

  @JsonProperty("treatmentSuspension")
  private TreatmentSuspension treatmentSuspension = null;

  public CustomerUpdate name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Customer Name, SV_MAPPING:Cust_Acct.CustAcctName_X
   * @return name
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Customer Name, SV_MAPPING:Cust_Acct.CustAcctName_X")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomerUpdate status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Customer status, SV_MAPPING:Cust_Acct.CustStatus_R
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Customer status, SV_MAPPING:Cust_Acct.CustStatus_R")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CustomerUpdate statusChangeReason(String statusChangeReason) {
    this.statusChangeReason = statusChangeReason;
    return this;
  }

   /**
   * Customer Status Change Reason. SV_MAPPING:Cust_Acct.CustStatusChangeReason_X.
   * @return statusChangeReason
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Customer Status Change Reason. SV_MAPPING:Cust_Acct.CustStatusChangeReason_X.")
  public String getStatusChangeReason() {
    return statusChangeReason;
  }

  public void setStatusChangeReason(String statusChangeReason) {
    this.statusChangeReason = statusChangeReason;
  }

  public CustomerUpdate validFor(TimePeriod validFor) {
    this.validFor = validFor;
    return this;
  }

   /**
   * Get validFor
   * @return validFor
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public TimePeriod getValidFor() {
    return validFor;
  }

  public void setValidFor(TimePeriod validFor) {
    this.validFor = validFor;
  }

  public CustomerUpdate engagedParty(List<PartyRef> engagedParty) {
    this.engagedParty = engagedParty;
    return this;
  }

  public CustomerUpdate addEngagedPartyItem(PartyRef engagedPartyItem) {
    if (this.engagedParty == null) {
      this.engagedParty = new ArrayList<PartyRef>();
    }
    this.engagedParty.add(engagedPartyItem);
    return this;
  }

   /**
   * Describes defines people who are contacts for a customer. Note: Only id, role and op are supported.
   * @return engagedParty
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes defines people who are contacts for a customer. Note: Only id, role and op are supported.")
  public List<PartyRef> getEngagedParty() {
    return engagedParty;
  }

  public void setEngagedParty(List<PartyRef> engagedParty) {
    this.engagedParty = engagedParty;
  }

  public CustomerUpdate characteristic(List<Characteristic> characteristic) {
    this.characteristic = characteristic;
    return this;
  }

  public CustomerUpdate addCharacteristicItem(Characteristic characteristicItem) {
    if (this.characteristic == null) {
      this.characteristic = new ArrayList<Characteristic>();
    }
    this.characteristic.add(characteristicItem);
    return this;
  }

   /**
   * Characteristic name supported: CustomerType | IndustryType | CustomerVatNumber | SalesRepresentative | CompanyNumber | CompanyType | CompanyRegistrationNumber | CUGId | EmployeeCount | FoundedDate | CustomerRank | VATExempt | OfficialLetterRequired | SpecialistCSR | PaysForSelf | PaysBySalary | PaymentDueDateOffset | PaymentDueDatePreference | VoucherTopUpStatus | ApartmentOwner | EncouragementDiscountPlan | AdminNumber | DoorLockPin | OfficerCSR | ResponsibleTeam | SubTeam | PaymentDueDateUOM | MaximumInvoiceAmountPayableCompany | PartialAmount. Characteristic value supported: SV_MAPPING:Cust_Acct.Type_R, SV_MAPPING:Cust_Acct.Industry_R, SV_MAPPING:Cust_Acct.UI_CustomerVATNumber_X, SV_MAPPING:Cust_Acct.SalesRepresentative_R, SV_MAPPING:Cust_Acct.CompanyNum_X, SV_MAPPING:Cust_Acct.CompanyType_R, SV_MAPPING:Cust_Acct.CompanyRegNum_X, SV_MAPPING:Cust_Acct.CorporateIdentifier_X, SV_MAPPING:Cust_Acct.Employee_Count_I, SV_MAPPING:Cust_Acct.Founded_Date_T, SV_MAPPING:Cust_Acct.CustomerRank_R, SV_MAPPING:Cust_Acct.VatExempt_B, SV_MAPPING:Cust_Acct.OfficialLetterReq_B, SV_MAPPING:Cust_Acct.SpecialistCSR_R, SV_MAPPING:Cust_Acct.PaysForSelf_B, SV_MAPPING:Cust_Acct.PaysBySalary_B, SV_MAPPING:Cust_Acct.PaymentOffsetDays_I, SV_MAPPING:Cust_Acct.PaymentDuePref_R, SV_MAPPING:Cust_Acct.VoucherTopUpStatus_B, SV_MAPPING:Cust_Acct.ApartmentOwner_R, SV_MAPPING:Cust_Acct.DiscountPlan_R, SV_MAPPING:Cust_Acct.AdminNumber_X, SV_MAPPING:Cust_Acct.DoorLockPin_X, SV_MAPPING:Cust_Acct.OfficerCSR_R, SV_MAPPING:Cust_Acct.ResponseTeam_R, SV_MAPPING:Cust_Acct.SubTeam_R, SV_MAPPING:Cust_Acct.PaymentDueDateUOM_R, SV_MAPPING:Cust_Acct.MaxInvAmtPayByComp_R, SV_MAPPING:Cust_Acct.MaxInvAmtPayByComp_C. Characteristic value type supported: string
   * @return characteristic
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Characteristic name supported: CustomerType | IndustryType | CustomerVatNumber | SalesRepresentative | CompanyNumber | CompanyType | CompanyRegistrationNumber | CUGId | EmployeeCount | FoundedDate | CustomerRank | VATExempt | OfficialLetterRequired | SpecialistCSR | PaysForSelf | PaysBySalary | PaymentDueDateOffset | PaymentDueDatePreference | VoucherTopUpStatus | ApartmentOwner | EncouragementDiscountPlan | AdminNumber | DoorLockPin | OfficerCSR | ResponsibleTeam | SubTeam | PaymentDueDateUOM | MaximumInvoiceAmountPayableCompany | PartialAmount. Characteristic value supported: SV_MAPPING:Cust_Acct.Type_R, SV_MAPPING:Cust_Acct.Industry_R, SV_MAPPING:Cust_Acct.UI_CustomerVATNumber_X, SV_MAPPING:Cust_Acct.SalesRepresentative_R, SV_MAPPING:Cust_Acct.CompanyNum_X, SV_MAPPING:Cust_Acct.CompanyType_R, SV_MAPPING:Cust_Acct.CompanyRegNum_X, SV_MAPPING:Cust_Acct.CorporateIdentifier_X, SV_MAPPING:Cust_Acct.Employee_Count_I, SV_MAPPING:Cust_Acct.Founded_Date_T, SV_MAPPING:Cust_Acct.CustomerRank_R, SV_MAPPING:Cust_Acct.VatExempt_B, SV_MAPPING:Cust_Acct.OfficialLetterReq_B, SV_MAPPING:Cust_Acct.SpecialistCSR_R, SV_MAPPING:Cust_Acct.PaysForSelf_B, SV_MAPPING:Cust_Acct.PaysBySalary_B, SV_MAPPING:Cust_Acct.PaymentOffsetDays_I, SV_MAPPING:Cust_Acct.PaymentDuePref_R, SV_MAPPING:Cust_Acct.VoucherTopUpStatus_B, SV_MAPPING:Cust_Acct.ApartmentOwner_R, SV_MAPPING:Cust_Acct.DiscountPlan_R, SV_MAPPING:Cust_Acct.AdminNumber_X, SV_MAPPING:Cust_Acct.DoorLockPin_X, SV_MAPPING:Cust_Acct.OfficerCSR_R, SV_MAPPING:Cust_Acct.ResponseTeam_R, SV_MAPPING:Cust_Acct.SubTeam_R, SV_MAPPING:Cust_Acct.PaymentDueDateUOM_R, SV_MAPPING:Cust_Acct.MaxInvAmtPayByComp_R, SV_MAPPING:Cust_Acct.MaxInvAmtPayByComp_C. Characteristic value type supported: string")
  public List<Characteristic> getCharacteristic() {
    return characteristic;
  }

  public void setCharacteristic(List<Characteristic> characteristic) {
    this.characteristic = characteristic;
  }

  public CustomerUpdate relatedParty(List<PartyRef> relatedParty) {
    this.relatedParty = relatedParty;
    return this;
  }

  public CustomerUpdate addRelatedPartyItem(PartyRef relatedPartyItem) {
    if (this.relatedParty == null) {
      this.relatedParty = new ArrayList<PartyRef>();
    }
    this.relatedParty.add(relatedPartyItem);
    return this;
  }

   /**
   * Describes the parent account of a customer. Note: Only id and role are supported.
   * @return relatedParty
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the parent account of a customer. Note: Only id and role are supported.")
  public List<PartyRef> getRelatedParty() {
    return relatedParty;
  }

  public void setRelatedParty(List<PartyRef> relatedParty) {
    this.relatedParty = relatedParty;
  }

  public CustomerUpdate account(List<AccountRef> account) {
    this.account = account;
    return this;
  }

  public CustomerUpdate addAccountItem(AccountRef accountItem) {
    if (this.account == null) {
      this.account = new ArrayList<AccountRef>();
    }
    this.account.add(accountItem);
    return this;
  }

   /**
   * Describes the customer primary account details. Note: Only billStructure and paymentPlan are support.
   * @return account
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the customer primary account details. Note: Only billStructure and paymentPlan are support.")
  public List<AccountRef> getAccount() {
    return account;
  }

  public void setAccount(List<AccountRef> account) {
    this.account = account;
  }

  public CustomerUpdate creditProfile(CreditProfile creditProfile) {
    this.creditProfile = creditProfile;
    return this;
  }

   /**
   * Get creditProfile
   * @return creditProfile
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public CreditProfile getCreditProfile() {
    return creditProfile;
  }

  public void setCreditProfile(CreditProfile creditProfile) {
    this.creditProfile = creditProfile;
  }

  public CustomerUpdate paymentMethod(List<PaymentMethodRef> paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

  public CustomerUpdate addPaymentMethodItem(PaymentMethodRef paymentMethodItem) {
    if (this.paymentMethod == null) {
      this.paymentMethod = new ArrayList<PaymentMethodRef>();
    }
    this.paymentMethod.add(paymentMethodItem);
    return this;
  }

   /**
   * Describes the customer payment methods. Note: status is not supported.
   * @return paymentMethod
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the customer payment methods. Note: status is not supported.")
  public List<PaymentMethodRef> getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(List<PaymentMethodRef> paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public CustomerUpdate contactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
    return this;
  }

  public CustomerUpdate addContactMediumItem(ContactMedium contactMediumItem) {
    if (this.contactMedium == null) {
      this.contactMedium = new ArrayList<ContactMedium>();
    }
    this.contactMedium.add(contactMediumItem);
    return this;
  }

   /**
   * Describes the customer contact medium details. Note: phoneNumber is not supported.
   * @return contactMedium
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the customer contact medium details. Note: phoneNumber is not supported.")
  public List<ContactMedium> getContactMedium() {
    return contactMedium;
  }

  public void setContactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
  }

  public CustomerUpdate taxExemptionCertificate(List<TaxExemptionCertificate> taxExemptionCertificate) {
    this.taxExemptionCertificate = taxExemptionCertificate;
    return this;
  }

  public CustomerUpdate addTaxExemptionCertificateItem(TaxExemptionCertificate taxExemptionCertificateItem) {
    if (this.taxExemptionCertificate == null) {
      this.taxExemptionCertificate = new ArrayList<TaxExemptionCertificate>();
    }
    this.taxExemptionCertificate.add(taxExemptionCertificateItem);
    return this;
  }

   /**
   * Get taxExemptionCertificate
   * @return taxExemptionCertificate
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<TaxExemptionCertificate> getTaxExemptionCertificate() {
    return taxExemptionCertificate;
  }

  public void setTaxExemptionCertificate(List<TaxExemptionCertificate> taxExemptionCertificate) {
    this.taxExemptionCertificate = taxExemptionCertificate;
  }

  public CustomerUpdate treatmentExemption(TreatmentExemption treatmentExemption) {
    this.treatmentExemption = treatmentExemption;
    return this;
  }

   /**
   * Get treatmentExemption
   * @return treatmentExemption
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public TreatmentExemption getTreatmentExemption() {
    return treatmentExemption;
  }

  public void setTreatmentExemption(TreatmentExemption treatmentExemption) {
    this.treatmentExemption = treatmentExemption;
  }

  public CustomerUpdate _case(CaseRef _case) {
    this._case = _case;
    return this;
  }

   /**
   * Get _case
   * @return _case
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public CaseRef getCase() {
    return _case;
  }

  public void setCase(CaseRef _case) {
    this._case = _case;
  }

  public CustomerUpdate treatmentSuspension(TreatmentSuspension treatmentSuspension) {
    this.treatmentSuspension = treatmentSuspension;
    return this;
  }

   /**
   * Get treatmentSuspension
   * @return treatmentSuspension
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public TreatmentSuspension getTreatmentSuspension() {
    return treatmentSuspension;
  }

  public void setTreatmentSuspension(TreatmentSuspension treatmentSuspension) {
    this.treatmentSuspension = treatmentSuspension;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerUpdate customerUpdate = (CustomerUpdate) o;
    return Objects.equals(this.name, customerUpdate.name) &&
        Objects.equals(this.status, customerUpdate.status) &&
        Objects.equals(this.statusChangeReason, customerUpdate.statusChangeReason) &&
        Objects.equals(this.validFor, customerUpdate.validFor) &&
        Objects.equals(this.engagedParty, customerUpdate.engagedParty) &&
        Objects.equals(this.characteristic, customerUpdate.characteristic) &&
        Objects.equals(this.relatedParty, customerUpdate.relatedParty) &&
        Objects.equals(this.account, customerUpdate.account) &&
        Objects.equals(this.creditProfile, customerUpdate.creditProfile) &&
        Objects.equals(this.paymentMethod, customerUpdate.paymentMethod) &&
        Objects.equals(this.contactMedium, customerUpdate.contactMedium) &&
        Objects.equals(this.taxExemptionCertificate, customerUpdate.taxExemptionCertificate) &&
        Objects.equals(this.treatmentExemption, customerUpdate.treatmentExemption) &&
        Objects.equals(this._case, customerUpdate._case) &&
        Objects.equals(this.treatmentSuspension, customerUpdate.treatmentSuspension);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status, statusChangeReason, validFor, engagedParty, characteristic, relatedParty, account, creditProfile, paymentMethod, contactMedium, taxExemptionCertificate, treatmentExemption, _case, treatmentSuspension);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerUpdate {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusChangeReason: ").append(toIndentedString(statusChangeReason)).append("\n");
    sb.append("    validFor: ").append(toIndentedString(validFor)).append("\n");
    sb.append("    engagedParty: ").append(toIndentedString(engagedParty)).append("\n");
    sb.append("    characteristic: ").append(toIndentedString(characteristic)).append("\n");
    sb.append("    relatedParty: ").append(toIndentedString(relatedParty)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    creditProfile: ").append(toIndentedString(creditProfile)).append("\n");
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    contactMedium: ").append(toIndentedString(contactMedium)).append("\n");
    sb.append("    taxExemptionCertificate: ").append(toIndentedString(taxExemptionCertificate)).append("\n");
    sb.append("    treatmentExemption: ").append(toIndentedString(treatmentExemption)).append("\n");
    sb.append("    _case: ").append(toIndentedString(_case)).append("\n");
    sb.append("    treatmentSuspension: ").append(toIndentedString(treatmentSuspension)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
