/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * The customer bill cycle.
 */
@Schema(description = "The customer bill cycle.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class CycleSpecification {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("preferredCurrency")
  private String preferredCurrency = null;

  @JsonProperty("reportLevel")
  private String reportLevel = null;

  @JsonProperty("suppressBilling")
  private String suppressBilling = null;

  @JsonProperty("suppressCycles")
  private String suppressCycles = null;

  @JsonProperty("suppressUntilDate")
  private String suppressUntilDate = null;

  @JsonProperty("transferredAccountNumber")
  private String transferredAccountNumber = null;

  @JsonProperty("billEndDate")
  private String billEndDate = null;

  public CycleSpecification name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Schedule Name, SV_MAPPING:Cust_Acct.InvoiceCycle_R
   * @return name
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Schedule Name, SV_MAPPING:Cust_Acct.InvoiceCycle_R")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CycleSpecification preferredCurrency(String preferredCurrency) {
    this.preferredCurrency = preferredCurrency;
    return this;
  }

   /**
   * Preferred Currency, SV_MAPPING:Cust_Acct.Currency_R
   * @return preferredCurrency
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Preferred Currency, SV_MAPPING:Cust_Acct.Currency_R")
  public String getPreferredCurrency() {
    return preferredCurrency;
  }

  public void setPreferredCurrency(String preferredCurrency) {
    this.preferredCurrency = preferredCurrency;
  }

  public CycleSpecification reportLevel(String reportLevel) {
    this.reportLevel = reportLevel;
    return this;
  }

   /**
   * Report Level, SV_MAPPING:Cust_Acct.ReportLevel_R
   * @return reportLevel
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Report Level, SV_MAPPING:Cust_Acct.ReportLevel_R")
  public String getReportLevel() {
    return reportLevel;
  }

  public void setReportLevel(String reportLevel) {
    this.reportLevel = reportLevel;
  }

  public CycleSpecification suppressBilling(String suppressBilling) {
    this.suppressBilling = suppressBilling;
    return this;
  }

   /**
   * Suppress Billing Flag, SV_MAPPING:Cust_Acct.SuppressBilling_B, Possible value 1 and 0
   * @return suppressBilling
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Suppress Billing Flag, SV_MAPPING:Cust_Acct.SuppressBilling_B, Possible value 1 and 0")
  public String getSuppressBilling() {
    return suppressBilling;
  }

  public void setSuppressBilling(String suppressBilling) {
    this.suppressBilling = suppressBilling;
  }

  public CycleSpecification suppressCycles(String suppressCycles) {
    this.suppressCycles = suppressCycles;
    return this;
  }

   /**
   * Suppress for number of Cycles, SV_MAPPING:Cust_Acct.SuppressCycles_I
   * @return suppressCycles
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Suppress for number of Cycles, SV_MAPPING:Cust_Acct.SuppressCycles_I")
  public String getSuppressCycles() {
    return suppressCycles;
  }

  public void setSuppressCycles(String suppressCycles) {
    this.suppressCycles = suppressCycles;
  }

  public CycleSpecification suppressUntilDate(String suppressUntilDate) {
    this.suppressUntilDate = suppressUntilDate;
    return this;
  }

   /**
   * Bill suppress date, SV_MAPPING:Cust_Acct.SuppressDate_T
   * @return suppressUntilDate
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Bill suppress date, SV_MAPPING:Cust_Acct.SuppressDate_T")
  public String getSuppressUntilDate() {
    return suppressUntilDate;
  }

  public void setSuppressUntilDate(String suppressUntilDate) {
    this.suppressUntilDate = suppressUntilDate;
  }

  public CycleSpecification transferredAccountNumber(String transferredAccountNumber) {
    this.transferredAccountNumber = transferredAccountNumber;
    return this;
  }

   /**
   * Transferred account number. SV_MAPPING:Cust_Acct.TransferAccountNumber_X
   * @return transferredAccountNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Transferred account number. SV_MAPPING:Cust_Acct.TransferAccountNumber_X")
  public String getTransferredAccountNumber() {
    return transferredAccountNumber;
  }

  public void setTransferredAccountNumber(String transferredAccountNumber) {
    this.transferredAccountNumber = transferredAccountNumber;
  }

  public CycleSpecification billEndDate(String billEndDate) {
    this.billEndDate = billEndDate;
    return this;
  }

   /**
   * Bill End Date. Describes the Bill cycle end date
   * @return billEndDate
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Bill End Date. Describes the Bill cycle end date")
  public String getBillEndDate() {
    return billEndDate;
  }

  public void setBillEndDate(String billEndDate) {
    this.billEndDate = billEndDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CycleSpecification cycleSpecification = (CycleSpecification) o;
    return Objects.equals(this.name, cycleSpecification.name) &&
        Objects.equals(this.preferredCurrency, cycleSpecification.preferredCurrency) &&
        Objects.equals(this.reportLevel, cycleSpecification.reportLevel) &&
        Objects.equals(this.suppressBilling, cycleSpecification.suppressBilling) &&
        Objects.equals(this.suppressCycles, cycleSpecification.suppressCycles) &&
        Objects.equals(this.suppressUntilDate, cycleSpecification.suppressUntilDate) &&
        Objects.equals(this.transferredAccountNumber, cycleSpecification.transferredAccountNumber) &&
        Objects.equals(this.billEndDate, cycleSpecification.billEndDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, preferredCurrency, reportLevel, suppressBilling, suppressCycles, suppressUntilDate, transferredAccountNumber, billEndDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CycleSpecification {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    preferredCurrency: ").append(toIndentedString(preferredCurrency)).append("\n");
    sb.append("    reportLevel: ").append(toIndentedString(reportLevel)).append("\n");
    sb.append("    suppressBilling: ").append(toIndentedString(suppressBilling)).append("\n");
    sb.append("    suppressCycles: ").append(toIndentedString(suppressCycles)).append("\n");
    sb.append("    suppressUntilDate: ").append(toIndentedString(suppressUntilDate)).append("\n");
    sb.append("    transferredAccountNumber: ").append(toIndentedString(transferredAccountNumber)).append("\n");
    sb.append("    billEndDate: ").append(toIndentedString(billEndDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
