/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.Objects;
/**
 * Customer treatment process.
 */
@Schema(description = "Customer treatment process.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class DunningCase {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("currentAmountDue")
  private Money currentAmountDue = null;

  public DunningCase id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Treatment query id. SV_MAPPING: CustAcctQuery.QueryID_I
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment query id. SV_MAPPING: CustAcctQuery.QueryID_I")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DunningCase name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Treatment query number. SV_MAPPING: CustAcctQuery.Name
   * @return name
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment query number. SV_MAPPING: CustAcctQuery.Name")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public DunningCase href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Not implemented yet
   * @return href
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Not implemented yet")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public DunningCase status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Treatment query status. SV_MAPPING: CustAcctQuery.QueryStatus_R
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment query status. SV_MAPPING: CustAcctQuery.QueryStatus_R")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public DunningCase currentAmountDue(Money currentAmountDue) {
    this.currentAmountDue = currentAmountDue;
    return this;
  }

   /**
   * Get currentAmountDue
   * @return currentAmountDue
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public Money getCurrentAmountDue() {
    return currentAmountDue;
  }

  public void setCurrentAmountDue(Money currentAmountDue) {
    this.currentAmountDue = currentAmountDue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DunningCase dunningCase = (DunningCase) o;
    return Objects.equals(this.id, dunningCase.id) &&
        Objects.equals(this.name, dunningCase.name) &&
        Objects.equals(this.href, dunningCase.href) &&
        Objects.equals(this.status, dunningCase.status) &&
        Objects.equals(this.currentAmountDue, dunningCase.currentAmountDue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, href, status, currentAmountDue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DunningCase {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    currentAmountDue: ").append(toIndentedString(currentAmountDue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
