/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Describes the contact medium characteristics that could be used to contact a party
 */
@Schema(description = "Describes the contact medium characteristics that could be used to contact a party")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class MediumCharacteristic {
  @JsonProperty("street1")
  private String street1 = null;

  @JsonProperty("street2")
  private String street2 = null;

  @JsonProperty("suburb")
  private String suburb = null;

  @JsonProperty("city")
  private String city = null;

  @JsonProperty("postCode")
  private String postCode = null;

  @JsonProperty("stateOrProvince")
  private String stateOrProvince = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("addressLine1")
  private String addressLine1 = null;

  @JsonProperty("geocode")
  private String geocode = null;

  @JsonProperty("subDoorNumber")
  private String subDoorNumber = null;

  @JsonProperty("genericAddress")
  private String genericAddress = null;

  @JsonProperty("phoneNumber")
  private String phoneNumber = null;

  public MediumCharacteristic street1(String street1) {
    this.street1 = street1;
    return this;
  }

   /**
   * Line 1, SV_MAPPING: Cust_Acct.PostalLine1_X | Cust_Acct.SiteLine1_X
   * @return street1
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Line 1, SV_MAPPING: Cust_Acct.PostalLine1_X | Cust_Acct.SiteLine1_X")
  public String getStreet1() {
    return street1;
  }

  public void setStreet1(String street1) {
    this.street1 = street1;
  }

  public MediumCharacteristic street2(String street2) {
    this.street2 = street2;
    return this;
  }

   /**
   * Line 2, SV_MAPPING: Cust_Acct.PostalLine2_X | Cust_Acct.SiteLine2_X
   * @return street2
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Line 2, SV_MAPPING: Cust_Acct.PostalLine2_X | Cust_Acct.SiteLine2_X")
  public String getStreet2() {
    return street2;
  }

  public void setStreet2(String street2) {
    this.street2 = street2;
  }

  public MediumCharacteristic suburb(String suburb) {
    this.suburb = suburb;
    return this;
  }

   /**
   * Suburban, SV_MAPPING: Cust_Acct.PostalSubDistrict_R | Cust_Acct.SiteSubDistrict_R
   * @return suburb
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Suburban, SV_MAPPING: Cust_Acct.PostalSubDistrict_R | Cust_Acct.SiteSubDistrict_R")
  public String getSuburb() {
    return suburb;
  }

  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }

  public MediumCharacteristic city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City, SV_MAPPING: Cust_Acct.PostalCity_R | Cust_Acct.SiteCity_R
   * @return city
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "City, SV_MAPPING: Cust_Acct.PostalCity_R | Cust_Acct.SiteCity_R")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public MediumCharacteristic postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * Post Code, SV_MAPPING: Cust_Acct.PostalPostCode_X | Cust_Acct.SitePostCode_X
   * @return postCode
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Post Code, SV_MAPPING: Cust_Acct.PostalPostCode_X | Cust_Acct.SitePostCode_X")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  public MediumCharacteristic stateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
    return this;
  }

   /**
   * State, SV_MAPPING: Cust_Acct.PostalDistrict_R | Cust_Acct.SiteDistrict_R
   * @return stateOrProvince
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "State, SV_MAPPING: Cust_Acct.PostalDistrict_R | Cust_Acct.SiteDistrict_R")
  public String getStateOrProvince() {
    return stateOrProvince;
  }

  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public MediumCharacteristic country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country, SV_MAPPING: Cust_Acct.PostalCountry_R | Cust_Acct.SiteCountry_R
   * @return country
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Country, SV_MAPPING: Cust_Acct.PostalCountry_R | Cust_Acct.SiteCountry_R")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public MediumCharacteristic addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * Address line 1, SV_MAPPING: Cust_Acct.PostalLine7_X | Cust_Acct.SiteLine7_X
   * @return addressLine1
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Address line 1, SV_MAPPING: Cust_Acct.PostalLine7_X | Cust_Acct.SiteLine7_X")
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public MediumCharacteristic geocode(String geocode) {
    this.geocode = geocode;
    return this;
  }

   /**
   * What3words, SV_MAPPING: Cust_Acct.PostalGeocode_X | Cust_Acct.SiteGeocode_X
   * @return geocode
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "What3words, SV_MAPPING: Cust_Acct.PostalGeocode_X | Cust_Acct.SiteGeocode_X")
  public String getGeocode() {
    return geocode;
  }

  public void setGeocode(String geocode) {
    this.geocode = geocode;
  }

  public MediumCharacteristic subDoorNumber(String subDoorNumber) {
    this.subDoorNumber = subDoorNumber;
    return this;
  }

   /**
   * Sub Door number, SV_MAPPING: Cust_Acct.PostalSubDoorNumber_X | Cust_Acct.SiteSubDoorNumber_X
   * @return subDoorNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Sub Door number, SV_MAPPING: Cust_Acct.PostalSubDoorNumber_X | Cust_Acct.SiteSubDoorNumber_X")
  public String getSubDoorNumber() {
    return subDoorNumber;
  }

  public void setSubDoorNumber(String subDoorNumber) {
    this.subDoorNumber = subDoorNumber;
  }

  public MediumCharacteristic genericAddress(String genericAddress) {
    this.genericAddress = genericAddress;
    return this;
  }

   /**
   * Generic Address when the actual address is not known, SV_MAPPING: Cust_Acct.PostalGenericAddress_X | Cust_Acct.SiteGenericAddress_X
   * @return genericAddress
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Generic Address when the actual address is not known, SV_MAPPING: Cust_Acct.PostalGenericAddress_X | Cust_Acct.SiteGenericAddress_X")
  public String getGenericAddress() {
    return genericAddress;
  }

  public void setGenericAddress(String genericAddress) {
    this.genericAddress = genericAddress;
  }

  public MediumCharacteristic phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * These are the phone numbers of the primary contact of customer. HomeNumber-&gt;SV_MAPPING:Contact.HomePhone_X,WorkNumber-&gt;SV_MAPPING:Contact.WorkPhone_X, MobileNumber-&gt;SV_MAPPING:Contact.MobilePhone_X
   * @return phoneNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "These are the phone numbers of the primary contact of customer. HomeNumber->SV_MAPPING:Contact.HomePhone_X,WorkNumber->SV_MAPPING:Contact.WorkPhone_X, MobileNumber->SV_MAPPING:Contact.MobilePhone_X")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediumCharacteristic mediumCharacteristic = (MediumCharacteristic) o;
    return Objects.equals(this.street1, mediumCharacteristic.street1) &&
        Objects.equals(this.street2, mediumCharacteristic.street2) &&
        Objects.equals(this.suburb, mediumCharacteristic.suburb) &&
        Objects.equals(this.city, mediumCharacteristic.city) &&
        Objects.equals(this.postCode, mediumCharacteristic.postCode) &&
        Objects.equals(this.stateOrProvince, mediumCharacteristic.stateOrProvince) &&
        Objects.equals(this.country, mediumCharacteristic.country) &&
        Objects.equals(this.addressLine1, mediumCharacteristic.addressLine1) &&
        Objects.equals(this.geocode, mediumCharacteristic.geocode) &&
        Objects.equals(this.subDoorNumber, mediumCharacteristic.subDoorNumber) &&
        Objects.equals(this.genericAddress, mediumCharacteristic.genericAddress) &&
        Objects.equals(this.phoneNumber, mediumCharacteristic.phoneNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(street1, street2, suburb, city, postCode, stateOrProvince, country, addressLine1, geocode, subDoorNumber, genericAddress, phoneNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediumCharacteristic {\n");
    
    sb.append("    street1: ").append(toIndentedString(street1)).append("\n");
    sb.append("    street2: ").append(toIndentedString(street2)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    geocode: ").append(toIndentedString(geocode)).append("\n");
    sb.append("    subDoorNumber: ").append(toIndentedString(subDoorNumber)).append("\n");
    sb.append("    genericAddress: ").append(toIndentedString(genericAddress)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
