/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Party reference. A party represents an organization or an individual.
 */
@Schema(description = "Party reference. A party represents an organization or an individual.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class PartyRef {
  @JsonProperty("@referredType")
  private String _atReferredType = null;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("role")
  private String role = null;

  @JsonProperty("individualIdentification")
  private List<IndividualIdentification> individualIdentification = null;

  @JsonProperty("partyCharacteristic")
  private List<Characteristic> partyCharacteristic = null;

  @JsonProperty("contactMedium")
  private List<ContactMedium> contactMedium = null;

  @JsonProperty("op")
  private String op = null;

  public PartyRef _atReferredType(String _atReferredType) {
    this._atReferredType = _atReferredType;
    return this;
  }

   /**
   * This is type of related party which it reffers, possible values individual, organization, customer. SV_MAPPING: perestapi.REFERRED_TYPE
   * @return _atReferredType
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "This is type of related party which it reffers, possible values individual, organization, customer. SV_MAPPING: perestapi.REFERRED_TYPE")
  public String getAtReferredType() {
    return _atReferredType;
  }

  public void setAtReferredType(String _atReferredType) {
    this._atReferredType = _atReferredType;
  }

  public PartyRef id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Contact Id, SV_MAPPING:contact.ObjectKey (Primary) or SV_MAPPING:contact.ObjectKey (Secondary) or Customer id, SV_MAPPING:Cust_Acct.ObjectKey
   * @return id
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Contact Id, SV_MAPPING:contact.ObjectKey (Primary) or SV_MAPPING:contact.ObjectKey (Secondary) or Customer id, SV_MAPPING:Cust_Acct.ObjectKey")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PartyRef href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Reference of the party - &lt;http://&lt;TREREST_HOSTNAME&gt;:&lt;TREREST_PORT&gt;/&lt;Party TreREST URL&gt;/&lt;contact.ObjectKey&gt;customer - &lt;http://&lt;TREREST_HOSTNAME&gt;:&lt;TREREST_PORT&gt;/&lt;customer TreREST URL&gt;/&lt;SV_MAPPING:Cust_Acct.ObjectKey&gt;
   * @return href
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Reference of the party - <http://<TREREST_HOSTNAME>:<TREREST_PORT>/<Party TreREST URL>/<contact.ObjectKey>customer - <http://<TREREST_HOSTNAME>:<TREREST_PORT>/<customer TreREST URL>/<SV_MAPPING:Cust_Acct.ObjectKey>")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public PartyRef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Contact display name, SV_MAPPING:contact.Display_Name, customer display name SV_MAPPING:Cust_Acct.CustAcctName_X or parent customer display name SV_MAPPING:Cust_Acct.ParentCustAcct_R@
   * @return name
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Contact display name, SV_MAPPING:contact.Display_Name, customer display name SV_MAPPING:Cust_Acct.CustAcctName_X or parent customer display name SV_MAPPING:Cust_Acct.ParentCustAcct_R@")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public PartyRef role(String role) {
    this.role = role;
    return this;
  }

   /**
   * Primary | Secondary | Parent | Child. SV_MAPPING: perestapi.RELATED_PARTY_ROLE
   * @return role
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Primary | Secondary | Parent | Child. SV_MAPPING: perestapi.RELATED_PARTY_ROLE")
  public String getRole() {
    return role;
  }

  public void setRole(String role) {
    this.role = role;
  }

  public PartyRef individualIdentification(List<IndividualIdentification> individualIdentification) {
    this.individualIdentification = individualIdentification;
    return this;
  }

  public PartyRef addIndividualIdentificationItem(IndividualIdentification individualIdentificationItem) {
    if (this.individualIdentification == null) {
      this.individualIdentification = new ArrayList<IndividualIdentification>();
    }
    this.individualIdentification.add(individualIdentificationItem);
    return this;
  }

   /**
   * Get individualIdentification
   * @return individualIdentification
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<IndividualIdentification> getIndividualIdentification() {
    return individualIdentification;
  }

  public void setIndividualIdentification(List<IndividualIdentification> individualIdentification) {
    this.individualIdentification = individualIdentification;
  }

  public PartyRef partyCharacteristic(List<Characteristic> partyCharacteristic) {
    this.partyCharacteristic = partyCharacteristic;
    return this;
  }

  public PartyRef addPartyCharacteristicItem(Characteristic partyCharacteristicItem) {
    if (this.partyCharacteristic == null) {
      this.partyCharacteristic = new ArrayList<Characteristic>();
    }
    this.partyCharacteristic.add(partyCharacteristicItem);
    return this;
  }

   /**
   * Characteristic name supported: PersonalVatNumber | CorporateVatNumber | ContactRole. Characteristic value supported: PersonalVatNumber -&gt; SV_MAPPING:Contact.General10_X | CorporateVatNumber -&gt; SV_MAPPING:Contact.General10_X | ContactRole -&gt; SV_MAPPING:perestapi.imp.CONTACT_ROLE. Characteristic value type supported: string
   * @return partyCharacteristic
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Characteristic name supported: PersonalVatNumber | CorporateVatNumber | ContactRole. Characteristic value supported: PersonalVatNumber -> SV_MAPPING:Contact.General10_X | CorporateVatNumber -> SV_MAPPING:Contact.General10_X | ContactRole -> SV_MAPPING:perestapi.imp.CONTACT_ROLE. Characteristic value type supported: string")
  public List<Characteristic> getPartyCharacteristic() {
    return partyCharacteristic;
  }

  public void setPartyCharacteristic(List<Characteristic> partyCharacteristic) {
    this.partyCharacteristic = partyCharacteristic;
  }

  public PartyRef contactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
    return this;
  }

  public PartyRef addContactMediumItem(ContactMedium contactMediumItem) {
    if (this.contactMedium == null) {
      this.contactMedium = new ArrayList<ContactMedium>();
    }
    this.contactMedium.add(contactMediumItem);
    return this;
  }

   /**
   * Get contactMedium
   * @return contactMedium
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<ContactMedium> getContactMedium() {
    return contactMedium;
  }

  public void setContactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
  }

  public PartyRef op(String op) {
    this.op = op;
    return this;
  }

   /**
   * add | replace | remove. SV_MAPPING: perestapi.OPERATION
   * @return op
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "add | replace | remove. SV_MAPPING: perestapi.OPERATION")
  public String getOp() {
    return op;
  }

  public void setOp(String op) {
    this.op = op;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PartyRef partyRef = (PartyRef) o;
    return Objects.equals(this._atReferredType, partyRef._atReferredType) &&
        Objects.equals(this.id, partyRef.id) &&
        Objects.equals(this.href, partyRef.href) &&
        Objects.equals(this.name, partyRef.name) &&
        Objects.equals(this.role, partyRef.role) &&
        Objects.equals(this.individualIdentification, partyRef.individualIdentification) &&
        Objects.equals(this.partyCharacteristic, partyRef.partyCharacteristic) &&
        Objects.equals(this.contactMedium, partyRef.contactMedium) &&
        Objects.equals(this.op, partyRef.op);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atReferredType, id, href, name, role, individualIdentification, partyCharacteristic, contactMedium, op);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PartyRef {\n");
    
    sb.append("    _atReferredType: ").append(toIndentedString(_atReferredType)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    role: ").append(toIndentedString(role)).append("\n");
    sb.append("    individualIdentification: ").append(toIndentedString(individualIdentification)).append("\n");
    sb.append("    partyCharacteristic: ").append(toIndentedString(partyCharacteristic)).append("\n");
    sb.append("    contactMedium: ").append(toIndentedString(contactMedium)).append("\n");
    sb.append("    op: ").append(toIndentedString(op)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
