/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * The payment plan that associated to the account.
 */
@Schema(description = "The payment plan that associated to the account.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class PaymentPlan {
  @JsonProperty("paymentMethod")
  private String paymentMethod = null;

  @JsonProperty("paymentLocation")
  private String paymentLocation = null;

  @JsonProperty("autoPay")
  private String autoPay = null;

  public PaymentPlan paymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
    return this;
  }

   /**
   * Payment method, SV_MAPPING:Cust_Acct.PayMethod_R
   * @return paymentMethod
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Payment method, SV_MAPPING:Cust_Acct.PayMethod_R")
  public String getPaymentMethod() {
    return paymentMethod;
  }

  public void setPaymentMethod(String paymentMethod) {
    this.paymentMethod = paymentMethod;
  }

  public PaymentPlan paymentLocation(String paymentLocation) {
    this.paymentLocation = paymentLocation;
    return this;
  }

   /**
   * Payment location, SV_MAPPING:Cust_Acct.PaymentLocation_R
   * @return paymentLocation
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Payment location, SV_MAPPING:Cust_Acct.PaymentLocation_R")
  public String getPaymentLocation() {
    return paymentLocation;
  }

  public void setPaymentLocation(String paymentLocation) {
    this.paymentLocation = paymentLocation;
  }

  public PaymentPlan autoPay(String autoPay) {
    this.autoPay = autoPay;
    return this;
  }

   /**
   * Describes the customer is registered for auto pay or not, SV_MAPPING:RT-YES_NO
   * @return autoPay
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the customer is registered for auto pay or not, SV_MAPPING:RT-YES_NO")
  public String getAutoPay() {
    return autoPay;
  }

  public void setAutoPay(String autoPay) {
    this.autoPay = autoPay;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentPlan paymentPlan = (PaymentPlan) o;
    return Objects.equals(this.paymentMethod, paymentPlan.paymentMethod) &&
        Objects.equals(this.paymentLocation, paymentPlan.paymentLocation) &&
        Objects.equals(this.autoPay, paymentPlan.autoPay);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentMethod, paymentLocation, autoPay);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentPlan {\n");
    
    sb.append("    paymentMethod: ").append(toIndentedString(paymentMethod)).append("\n");
    sb.append("    paymentLocation: ").append(toIndentedString(paymentLocation)).append("\n");
    sb.append("    autoPay: ").append(toIndentedString(autoPay)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
