/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.*;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;

import java.util.Objects;
/**
 * PaymentMethod reference. A payment method defines a specific mean of payment (e.g direct debit).
 */
@Schema(description = "PaymentMethod reference. A payment method defines a specific mean of payment (e.g direct debit).")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class PaymentMethodRef {
  /**
   * Payment method type i.e.: bankAccountDebit | bankCard. SV_MAPPING: perestapi.PAYMENT_METHOD_TYPE RT
   */
  public enum AtTypeEnum {
    BANKACCOUNTDEBIT("bankAccountDebit"),
    BANKCARD("bankCard");

    private String value;

    AtTypeEnum(String value) {
      this.value = value;
    }
    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    @JsonCreator
    public static AtTypeEnum fromValue(String input) {
      for (AtTypeEnum b : AtTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }

  }
  @JsonProperty("@type")
  private AtTypeEnum _atType = null;

  @JsonProperty("details")
  private Object details = null;

  public PaymentMethodRef _atType(AtTypeEnum _atType) {
    this._atType = _atType;
    return this;
  }

   /**
   * Payment method type i.e.: bankAccountDebit | bankCard. SV_MAPPING: perestapi.PAYMENT_METHOD_TYPE RT
   * @return _atType
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Payment method type i.e.: bankAccountDebit | bankCard. SV_MAPPING: perestapi.PAYMENT_METHOD_TYPE RT")
  public AtTypeEnum getAtType() {
    return _atType;
  }

  public void setAtType(AtTypeEnum _atType) {
    this._atType = _atType;
  }

  public PaymentMethodRef details(Object details) {
    this.details = details;
    return this;
  }

   /**
   * If @type is bankAccountDebit then the details attribute object values will be derived from BankAccountDebitType object type. If @type is bankCard then the details attribute object values will be derived from BankCardType object type
   * @return details
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "If @type is bankAccountDebit then the details attribute object values will be derived from BankAccountDebitType object type. If @type is bankCard then the details attribute object values will be derived from BankCardType object type")
  public Object getDetails() {
    return details;
  }

  public void setDetails(Object details) {
    this.details = details;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentMethodRef paymentMethodRef = (PaymentMethodRef) o;
    return Objects.equals(this._atType, paymentMethodRef._atType) &&
        Objects.equals(this.details, paymentMethodRef.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(_atType, details);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentMethodRef {\n");
    
    sb.append("    _atType: ").append(toIndentedString(_atType)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
