/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * A tax exemption certificate represents a tax exemption granted to a customer by a tax jurisdiction which may be a city, state, country.
 */
@Schema(description = "A tax exemption certificate represents a tax exemption granted to a customer by a tax jurisdiction which may be a city, state, country.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class TaxExemptionCertificate {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("documentId")
  private String documentId = null;

  @JsonProperty("description")
  private String description = null;

  @JsonProperty("validFor")
  private TimePeriod validFor = null;

  @JsonProperty("taxDefinition")
  private List<TaxDefinition> taxDefinition = null;

  public TaxExemptionCertificate id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Certificate, SV_MAPPING: CustAcctList.ResultFact01_X
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Certificate, SV_MAPPING: CustAcctList.ResultFact01_X")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TaxExemptionCertificate documentId(String documentId) {
    this.documentId = documentId;
    return this;
  }

   /**
   * Document id, SV_MAPPING: CustAcctList.ResultFact04_X
   * @return documentId
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Document id, SV_MAPPING: CustAcctList.ResultFact04_X")
  public String getDocumentId() {
    return documentId;
  }

  public void setDocumentId(String documentId) {
    this.documentId = documentId;
  }

  public TaxExemptionCertificate description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Document Description, SV_MAPPING: CustAcctList.ResultFact05_X
   * @return description
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Document Description, SV_MAPPING: CustAcctList.ResultFact05_X")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TaxExemptionCertificate validFor(TimePeriod validFor) {
    this.validFor = validFor;
    return this;
  }

   /**
   * Get validFor
   * @return validFor
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public TimePeriod getValidFor() {
    return validFor;
  }

  public void setValidFor(TimePeriod validFor) {
    this.validFor = validFor;
  }

  public TaxExemptionCertificate taxDefinition(List<TaxDefinition> taxDefinition) {
    this.taxDefinition = taxDefinition;
    return this;
  }

  public TaxExemptionCertificate addTaxDefinitionItem(TaxDefinition taxDefinitionItem) {
    if (this.taxDefinition == null) {
      this.taxDefinition = new ArrayList<TaxDefinition>();
    }
    this.taxDefinition.add(taxDefinitionItem);
    return this;
  }

   /**
   * Get taxDefinition
   * @return taxDefinition
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<TaxDefinition> getTaxDefinition() {
    return taxDefinition;
  }

  public void setTaxDefinition(List<TaxDefinition> taxDefinition) {
    this.taxDefinition = taxDefinition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TaxExemptionCertificate taxExemptionCertificate = (TaxExemptionCertificate) o;
    return Objects.equals(this.id, taxExemptionCertificate.id) &&
        Objects.equals(this.documentId, taxExemptionCertificate.documentId) &&
        Objects.equals(this.description, taxExemptionCertificate.description) &&
        Objects.equals(this.validFor, taxExemptionCertificate.validFor) &&
        Objects.equals(this.taxDefinition, taxExemptionCertificate.taxDefinition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, documentId, description, validFor, taxDefinition);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TaxExemptionCertificate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    documentId: ").append(toIndentedString(documentId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    validFor: ").append(toIndentedString(validFor)).append("\n");
    sb.append("    taxDefinition: ").append(toIndentedString(taxDefinition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
