/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.Date;
import java.util.Objects;
/**
 * Customer treatment suspension.
 */
@Schema(description = "Customer treatment suspension.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class TreatmentSuspension {
  @JsonProperty("suspensionReasonCode")
  private String suspensionReasonCode = null;

  @JsonProperty("suspensionEndDate")
  private Date suspensionEndDate = null;

  @JsonProperty("id")
  private String id = null;

  public TreatmentSuspension suspensionReasonCode(String suspensionReasonCode) {
    this.suspensionReasonCode = suspensionReasonCode;
    return this;
  }

   /**
   * Treatment Suspension reason code, fetched from customer DA List. If suspensionReasonCode is not passed in the request or null then its delete suspension record from Treatment Suspension Attributes customer DA.SV_MAPPING:CustAcctList.ResultFact01_X
   * @return suspensionReasonCode
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment Suspension reason code, fetched from customer DA List. If suspensionReasonCode is not passed in the request or null then its delete suspension record from Treatment Suspension Attributes customer DA.SV_MAPPING:CustAcctList.ResultFact01_X")
  public String getSuspensionReasonCode() {
    return suspensionReasonCode;
  }

  public void setSuspensionReasonCode(String suspensionReasonCode) {
    this.suspensionReasonCode = suspensionReasonCode;
  }

  public TreatmentSuspension suspensionEndDate(Date suspensionEndDate) {
    this.suspensionEndDate = suspensionEndDate;
    return this;
  }

   /**
   * Suspension End Date,fetched from customer DA List. SV_MAPPING:CustAcctList.ResultFact02_X
   * @return suspensionEndDate
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Suspension End Date,fetched from customer DA List. SV_MAPPING:CustAcctList.ResultFact02_X")
  public Date getSuspensionEndDate() {
    return suspensionEndDate;
  }

  public void setSuspensionEndDate(Date suspensionEndDate) {
    this.suspensionEndDate = suspensionEndDate;
  }

  public TreatmentSuspension id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Treatment suspension derived attribute id, this is only used in case of GET Customer API. SV_MAPPING: CustAcctList.CustListID_I
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment suspension derived attribute id, this is only used in case of GET Customer API. SV_MAPPING: CustAcctList.CustListID_I")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreatmentSuspension treatmentSuspension = (TreatmentSuspension) o;
    return Objects.equals(this.suspensionReasonCode, treatmentSuspension.suspensionReasonCode) &&
        Objects.equals(this.suspensionEndDate, treatmentSuspension.suspensionEndDate) &&
        Objects.equals(this.id, treatmentSuspension.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(suspensionReasonCode, suspensionEndDate, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreatmentSuspension {\n");
    
    sb.append("    suspensionReasonCode: ").append(toIndentedString(suspensionReasonCode)).append("\n");
    sb.append("    suspensionEndDate: ").append(toIndentedString(suspensionEndDate)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
