/*
 * Customer Management
 * This is Swagger specification for the TMF Customer Management.
 *
 * OpenAPI spec version: $Revision: 1.40 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.customer;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Customer treatment exemption.
 */
@Schema(description = "Customer treatment exemption.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T13:05:19.553816+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class TreatmentExemption {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("exemption")
  private String exemption = null;

  @JsonProperty("description")
  private String description = null;

  public TreatmentExemption id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Treatment exemption derived attribute id, SV_MAPPING: CustAcctList.CustListID_I
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment exemption derived attribute id, SV_MAPPING: CustAcctList.CustListID_I")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TreatmentExemption exemption(String exemption) {
    this.exemption = exemption;
    return this;
  }

   /**
   * Treatment exemption flag, SV_MAPPING: CustAcctList.IndexValue01_X
   * @return exemption
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment exemption flag, SV_MAPPING: CustAcctList.IndexValue01_X")
  public String getExemption() {
    return exemption;
  }

  public void setExemption(String exemption) {
    this.exemption = exemption;
  }

  public TreatmentExemption description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Treatment exemption description, SV_MAPPING: CustAcctList.Description_X
   * @return description
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Treatment exemption description, SV_MAPPING: CustAcctList.Description_X")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreatmentExemption treatmentExemption = (TreatmentExemption) o;
    return Objects.equals(this.id, treatmentExemption.id) &&
        Objects.equals(this.exemption, treatmentExemption.exemption) &&
        Objects.equals(this.description, treatmentExemption.description);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, exemption, description);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreatmentExemption {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    exemption: ").append(toIndentedString(exemption)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
