apiVersion: v1
kind: Secret
metadata:
  name: accountmanagement-secret
type: Opaque
data:
  application.properties: ZXh0ZXJuYWwuYXBpLmJpbGxpbmcuYXV0aD1CYXNpYyBWRkpGVWtWVFZEcFhiM0pyUm05eVFXbHlkR1ZzSkRFeU16UQo=
  application-ug-uat.properties: ZXh0ZXJuYWwuYXBpLmJpbGxpbmcuYXV0aD1CYXNpYyBWRkpGVWtWVFZEcFhiM0pyUm05eVFXbHlkR1ZzSkRFeU16UQo=
