/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Array of secondary email addresses(If multiple) with verification.
 */
@Schema(description = "Array of secondary email addresses(If multiple) with verification.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class AdditionalEmailAddressWithVerification {
  @JsonProperty("emailAddress")
  private String emailAddress = null;

  @JsonProperty("verified")
  private String verified = null;

  public AdditionalEmailAddressWithVerification emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * Secondary email addresses. SV_MAPPING:ContactComms.Address_X
   * @return emailAddress
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Secondary email addresses. SV_MAPPING:ContactComms.Address_X")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public AdditionalEmailAddressWithVerification verified(String verified) {
    this.verified = verified;
    return this;
  }

   /**
   * Specifies secondary emails are verified or not. SV_MAPPING:ContactComms.Verified_B
   * @return verified
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Specifies secondary emails are verified or not. SV_MAPPING:ContactComms.Verified_B")
  public String getVerified() {
    return verified;
  }

  public void setVerified(String verified) {
    this.verified = verified;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdditionalEmailAddressWithVerification additionalEmailAddressWithVerification = (AdditionalEmailAddressWithVerification) o;
    return Objects.equals(this.emailAddress, additionalEmailAddressWithVerification.emailAddress) &&
        Objects.equals(this.verified, additionalEmailAddressWithVerification.verified);
  }

  @Override
  public int hashCode() {
    return Objects.hash(emailAddress, verified);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdditionalEmailAddressWithVerification {\n");
    
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
