/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * The Case data structure
 */
@Schema(description = "The Case data structure")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class CaseRef {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("name")
  private String name = null;

  public CaseRef id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Identifier of the Case
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Identifier of the Case")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CaseRef href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Reference of the Case
   * @return href
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Reference of the Case")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public CaseRef status(String status) {
    this.status = status;
    return this;
  }

   /**
   * The Status of Case. Possible Values New/Open/Closed
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The Status of Case. Possible Values New/Open/Closed")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public CaseRef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the attachment
   * @return name
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The name of the attachment")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CaseRef caseRef = (CaseRef) o;
    return Objects.equals(this.id, caseRef.id) &&
        Objects.equals(this.href, caseRef.href) &&
        Objects.equals(this.status, caseRef.status) &&
        Objects.equals(this.name, caseRef.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, status, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CaseRef {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
