/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.Date;
import java.util.Objects;
/**
 * Effective date and time where an transaction take place
 */
@Schema(description = "Effective date and time where an transaction take place")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class EffectiveDate {
  @JsonProperty("effectiveStartDate")
  private Date effectiveStartDate = null;

  public EffectiveDate effectiveStartDate(Date effectiveStartDate) {
    this.effectiveStartDate = effectiveStartDate;
    return this;
  }

   /**
   * Start of the time period. Format: yyyy-mm-ddThh:nn:ss, SV_MAPPING:Contact.EffectiveStartDate_T
   * @return effectiveStartDate
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Start of the time period. Format: yyyy-mm-ddThh:nn:ss, SV_MAPPING:Contact.EffectiveStartDate_T")
  public Date getEffectiveStartDate() {
    return effectiveStartDate;
  }

  public void setEffectiveStartDate(Date effectiveStartDate) {
    this.effectiveStartDate = effectiveStartDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EffectiveDate effectiveDate = (EffectiveDate) o;
    return Objects.equals(this.effectiveStartDate, effectiveDate.effectiveStartDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(effectiveStartDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EffectiveDate {\n");
    
    sb.append("    effectiveStartDate: ").append(toIndentedString(effectiveStartDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
