/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Used when an API throws an Error, typically with a HTTP error response - code(3xx, 4xx, 5xx)
 */
@Schema(description = "Used when an API throws an Error, typically with a HTTP error response - code(3xx, 4xx, 5xx)")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class Error {
  @JsonProperty("code")
  private String code = null;

  @JsonProperty("reason")
  private String reason = null;

  @JsonProperty("message")
  private String message = null;

  @JsonProperty("action")
  private String action = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("referenceError")
  private String referenceError = null;

  @JsonProperty("@baseType")
  private String _atBaseType = null;

  @JsonProperty("@schemaLocation")
  private String _atSchemaLocation = null;

  @JsonProperty("@type")
  private String _atType = null;

  @JsonProperty("errorParams")
  private List<String> errorParams = null;

  public Error code(String code) {
    this.code = code;
    return this;
  }

   /**
   * Application relevant detail, defined in the API or a common list.
   * @return code
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Application relevant detail, defined in the API or a common list.")
  public String getCode() {
    return code;
  }

  public void setCode(String code) {
    this.code = code;
  }

  public Error reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Explanation of the reason for the error which can be shown to a client user.
   * @return reason
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "Explanation of the reason for the error which can be shown to a client user.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public Error message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Details information related to the error which can be shown to a client user.
   * @return message
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Details information related to the error which can be shown to a client user.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public Error action(String action) {
    this.action = action;
    return this;
  }

   /**
   * Corrective actions for the error which can be shown to a client user.
   * @return action
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Corrective actions for the error which can be shown to a client user.")
  public String getAction() {
    return action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public Error status(String status) {
    this.status = status;
    return this;
  }

   /**
   * HTTP Error code extension
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HTTP Error code extension")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Error referenceError(String referenceError) {
    this.referenceError = referenceError;
    return this;
  }

   /**
   * URI of documentation describing the error.
   * @return referenceError
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "URI of documentation describing the error.")
  public String getReferenceError() {
    return referenceError;
  }

  public void setReferenceError(String referenceError) {
    this.referenceError = referenceError;
  }

  public Error _atBaseType(String _atBaseType) {
    this._atBaseType = _atBaseType;
    return this;
  }

   /**
   * When sub - classing, this defines the super - class.
   * @return _atBaseType
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "When sub - classing, this defines the super - class.")
  public String getAtBaseType() {
    return _atBaseType;
  }

  public void setAtBaseType(String _atBaseType) {
    this._atBaseType = _atBaseType;
  }

  public Error _atSchemaLocation(String _atSchemaLocation) {
    this._atSchemaLocation = _atSchemaLocation;
    return this;
  }

   /**
   * A URI to a JSON - Schema file that defines additional attributes and relationships
   * @return _atSchemaLocation
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "A URI to a JSON - Schema file that defines additional attributes and relationships")
  public String getAtSchemaLocation() {
    return _atSchemaLocation;
  }

  public void setAtSchemaLocation(String _atSchemaLocation) {
    this._atSchemaLocation = _atSchemaLocation;
  }

  public Error _atType(String _atType) {
    this._atType = _atType;
    return this;
  }

   /**
   * &#x27;Error&#x27; indicates that the error message is of server error message, &#x27;Warning&#x27; indicates that the error message is of server warning message
   * @return _atType
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "'Error' indicates that the error message is of server error message, 'Warning' indicates that the error message is of server warning message")
  public String getAtType() {
    return _atType;
  }

  public void setAtType(String _atType) {
    this._atType = _atType;
  }

  public Error errorParams(List<String> errorParams) {
    this.errorParams = errorParams;
    return this;
  }

  public Error addErrorParamsItem(String errorParamsItem) {
    if (this.errorParams == null) {
      this.errorParams = new ArrayList<String>();
    }
    this.errorParams.add(errorParamsItem);
    return this;
  }

   /**
   * Get errorParams
   * @return errorParams
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<String> getErrorParams() {
    return errorParams;
  }

  public void setErrorParams(List<String> errorParams) {
    this.errorParams = errorParams;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Error error = (Error) o;
    return Objects.equals(this.code, error.code) &&
        Objects.equals(this.reason, error.reason) &&
        Objects.equals(this.message, error.message) &&
        Objects.equals(this.action, error.action) &&
        Objects.equals(this.status, error.status) &&
        Objects.equals(this.referenceError, error.referenceError) &&
        Objects.equals(this._atBaseType, error._atBaseType) &&
        Objects.equals(this._atSchemaLocation, error._atSchemaLocation) &&
        Objects.equals(this._atType, error._atType) &&
        Objects.equals(this.errorParams, error.errorParams);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, reason, message, action, status, referenceError, _atBaseType, _atSchemaLocation, _atType, errorParams);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Error {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    action: ").append(toIndentedString(action)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    referenceError: ").append(toIndentedString(referenceError)).append("\n");
    sb.append("    _atBaseType: ").append(toIndentedString(_atBaseType)).append("\n");
    sb.append("    _atSchemaLocation: ").append(toIndentedString(_atSchemaLocation)).append("\n");
    sb.append("    _atType: ").append(toIndentedString(_atType)).append("\n");
    sb.append("    errorParams: ").append(toIndentedString(errorParams)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
