/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Individual List
 */
@Schema(description = "Individual List")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class IndividualList {
  @JsonProperty("allObjKeys")
  private List<Long> allObjKeys = null;

  @JsonProperty("totalObjects")
  private Long totalObjects = null;

  @JsonProperty("individuals")
  private List<Individual> individuals = null;

  @JsonProperty("warningMessage")
  private String warningMessage = null;

  public IndividualList allObjKeys(List<Long> allObjKeys) {
    this.allObjKeys = allObjKeys;
    return this;
  }

  public IndividualList addAllObjKeysItem(Long allObjKeysItem) {
    if (this.allObjKeys == null) {
      this.allObjKeys = new ArrayList<Long>();
    }
    this.allObjKeys.add(allObjKeysItem);
    return this;
  }

   /**
   * All object keys which met search criteria. This information is used for pagination.
   * @return allObjKeys
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "All object keys which met search criteria. This information is used for pagination.")
  public List<Long> getAllObjKeys() {
    return allObjKeys;
  }

  public void setAllObjKeys(List<Long> allObjKeys) {
    this.allObjKeys = allObjKeys;
  }

  public IndividualList totalObjects(Long totalObjects) {
    this.totalObjects = totalObjects;
    return this;
  }

   /**
   * Total number of items matching criteria
   * @return totalObjects
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Total number of items matching criteria")
  public Long getTotalObjects() {
    return totalObjects;
  }

  public void setTotalObjects(Long totalObjects) {
    this.totalObjects = totalObjects;
  }

  public IndividualList individuals(List<Individual> individuals) {
    this.individuals = individuals;
    return this;
  }

  public IndividualList addIndividualsItem(Individual individualsItem) {
    if (this.individuals == null) {
      this.individuals = new ArrayList<Individual>();
    }
    this.individuals.add(individualsItem);
    return this;
  }

   /**
   * Describes the list of Individuals with details
   * @return individuals
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Describes the list of Individuals with details")
  public List<Individual> getIndividuals() {
    return individuals;
  }

  public void setIndividuals(List<Individual> individuals) {
    this.individuals = individuals;
  }

  public IndividualList warningMessage(String warningMessage) {
    this.warningMessage = warningMessage;
    return this;
  }

   /**
   * Warning message details.
   * @return warningMessage
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Warning message details.")
  public String getWarningMessage() {
    return warningMessage;
  }

  public void setWarningMessage(String warningMessage) {
    this.warningMessage = warningMessage;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualList individualList = (IndividualList) o;
    return Objects.equals(this.allObjKeys, individualList.allObjKeys) &&
        Objects.equals(this.totalObjects, individualList.totalObjects) &&
        Objects.equals(this.individuals, individualList.individuals) &&
        Objects.equals(this.warningMessage, individualList.warningMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(allObjKeys, totalObjects, individuals, warningMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualList {\n");
    
    sb.append("    allObjKeys: ").append(toIndentedString(allObjKeys)).append("\n");
    sb.append("    totalObjects: ").append(toIndentedString(totalObjects)).append("\n");
    sb.append("    individuals: ").append(toIndentedString(individuals)).append("\n");
    sb.append("    warningMessage: ").append(toIndentedString(warningMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
