/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Objects;
/**
 * Individual represents a single human being (a man, woman or child). The individual can be a customer, an employee or any other person that the organization needs to store information about. Skipped properties: id,href
 */
@Schema(description = "Individual represents a single human being (a man, woman or child). The individual can be a customer, an employee or any other person that the organization needs to store information about. Skipped properties: id,href")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class IndividualCreate {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("effectiveDate")
  private EffectiveDate effectiveDate = null;

  @JsonProperty("birthDate")
  @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
  private Date birthDate = null;

  @JsonProperty("familyName")
  private String familyName = null;

  @JsonProperty("familyNamePrefix")
  private String familyNamePrefix = null;

  @JsonProperty("gender")
  private String gender = null;

  @JsonProperty("givenName")
  private String givenName = null;

  @JsonProperty("legalName")
  private String legalName = null;

  @JsonProperty("maritalStatus")
  private String maritalStatus = null;

  @JsonProperty("nationality")
  private String nationality = null;

  @JsonProperty("preferredGivenName")
  private String preferredGivenName = null;

  @JsonProperty("title")
  private String title = null;

  @JsonProperty("case")
  private CaseRef _case = null;

  @JsonProperty("contactMedium")
  private List<ContactMedium> contactMedium = new ArrayList<ContactMedium>();

  @JsonProperty("disability")
  private List<Disability> disability = null;

  @JsonProperty("individualIdentification")
  private List<IndividualIdentification> individualIdentification = null;

  @JsonProperty("languageAbility")
  private List<LanguageAbility> languageAbility = null;

  @JsonProperty("partyCharacteristic")
  private List<Characteristic> partyCharacteristic = null;

  @JsonProperty("relatedParty")
  private List<RelatedParty> relatedParty = new ArrayList<RelatedParty>();

  @JsonProperty("skill")
  private List<Skill> skill = null;

  @JsonProperty("status")
  private String status = null;

  @JsonProperty("source")
  private String source = null;

  public IndividualCreate id(String id) {
    this.id = id;
    return this;
  }

   /**
   * SV_MAPPING:Contact.XSID
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "SV_MAPPING:Contact.XSID")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public IndividualCreate effectiveDate(EffectiveDate effectiveDate) {
    this.effectiveDate = effectiveDate;
    return this;
  }

   /**
   * Get effectiveDate
   * @return effectiveDate
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public EffectiveDate getEffectiveDate() {
    return effectiveDate;
  }

  public void setEffectiveDate(EffectiveDate effectiveDate) {
    this.effectiveDate = effectiveDate;
  }

  public IndividualCreate birthDate(Date birthDate) {
    this.birthDate = birthDate;
    return this;
  }

   /**
   * Format: yyyy-mm-ddThh:nn:ss, SV_MAPPING:Contact.BirthDate_T
   * @return birthDate
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Format: yyyy-mm-ddThh:nn:ss, SV_MAPPING:Contact.BirthDate_T")
  public Date getBirthDate() {
    return birthDate;
  }

  public void setBirthDate(Date birthDate) {
    this.birthDate = birthDate;
  }

  public IndividualCreate familyName(String familyName) {
    this.familyName = familyName;
    return this;
  }

   /**
   * SV_MAPPING:Contact.LastName_X
   * @return familyName
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "SV_MAPPING:Contact.LastName_X")
  public String getFamilyName() {
    return familyName;
  }

  public void setFamilyName(String familyName) {
    this.familyName = familyName;
  }

  public IndividualCreate familyNamePrefix(String familyNamePrefix) {
    this.familyNamePrefix = familyNamePrefix;
    return this;
  }

   /**
   * Family Name Prefix. SV_MAPPING:Contact.LastName2_X
   * @return familyNamePrefix
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Family Name Prefix. SV_MAPPING:Contact.LastName2_X")
  public String getFamilyNamePrefix() {
    return familyNamePrefix;
  }

  public void setFamilyNamePrefix(String familyNamePrefix) {
    this.familyNamePrefix = familyNamePrefix;
  }

  public IndividualCreate gender(String gender) {
    this.gender = gender;
    return this;
  }

   /**
   * Gender RT, SV_MAPPING:Contact.Sex_R
   * @return gender
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Gender RT, SV_MAPPING:Contact.Sex_R")
  public String getGender() {
    return gender;
  }

  public void setGender(String gender) {
    this.gender = gender;
  }

  public IndividualCreate givenName(String givenName) {
    this.givenName = givenName;
    return this;
  }

   /**
   * SV_MAPPING:Contact.FirstName_X
   * @return givenName
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "SV_MAPPING:Contact.FirstName_X")
  public String getGivenName() {
    return givenName;
  }

  public void setGivenName(String givenName) {
    this.givenName = givenName;
  }

  public IndividualCreate legalName(String legalName) {
    this.legalName = legalName;
    return this;
  }

   /**
   * SV_MAPPING:Contact.OfficialName_X
   * @return legalName
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "SV_MAPPING:Contact.OfficialName_X")
  public String getLegalName() {
    return legalName;
  }

  public void setLegalName(String legalName) {
    this.legalName = legalName;
  }

  public IndividualCreate maritalStatus(String maritalStatus) {
    this.maritalStatus = maritalStatus;
    return this;
  }

   /**
   * MARITAL_STATUS RT, SV_MAPPING:Contact.MaritalStatus_R
   * @return maritalStatus
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "MARITAL_STATUS RT, SV_MAPPING:Contact.MaritalStatus_R")
  public String getMaritalStatus() {
    return maritalStatus;
  }

  public void setMaritalStatus(String maritalStatus) {
    this.maritalStatus = maritalStatus;
  }

  public IndividualCreate nationality(String nationality) {
    this.nationality = nationality;
    return this;
  }

   /**
   * Nationality RT, SV_MAPPING:Contact.Nationality_R
   * @return nationality
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Nationality RT, SV_MAPPING:Contact.Nationality_R")
  public String getNationality() {
    return nationality;
  }

  public void setNationality(String nationality) {
    this.nationality = nationality;
  }

  public IndividualCreate preferredGivenName(String preferredGivenName) {
    this.preferredGivenName = preferredGivenName;
    return this;
  }

   /**
   * SV_MAPPING:Contact.PreferredName_X
   * @return preferredGivenName
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "SV_MAPPING:Contact.PreferredName_X")
  public String getPreferredGivenName() {
    return preferredGivenName;
  }

  public void setPreferredGivenName(String preferredGivenName) {
    this.preferredGivenName = preferredGivenName;
  }

  public IndividualCreate title(String title) {
    this.title = title;
    return this;
  }

   /**
   * Title RT, SV_MAPPING:Contact.Title_R
   * @return title
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Title RT, SV_MAPPING:Contact.Title_R")
  public String getTitle() {
    return title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public IndividualCreate _case(CaseRef _case) {
    this._case = _case;
    return this;
  }

   /**
   * Get _case
   * @return _case
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public CaseRef getCase() {
    return _case;
  }

  public void setCase(CaseRef _case) {
    this._case = _case;
  }

  public IndividualCreate contactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
    return this;
  }

  public IndividualCreate addContactMediumItem(ContactMedium contactMediumItem) {
    this.contactMedium.add(contactMediumItem);
    return this;
  }

   /**
   * At least one of HomeAddress | PostalAddress | WorkAddress is mandatory. At least one of HomeNumber | WorkNumber | MobileNumber |FaxNumber is mandatory
   * @return contactMedium
  **/
  @NotNull
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "At least one of HomeAddress | PostalAddress | WorkAddress is mandatory. At least one of HomeNumber | WorkNumber | MobileNumber |FaxNumber is mandatory")
  public List<ContactMedium> getContactMedium() {
    return contactMedium;
  }

  public void setContactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
  }

  public IndividualCreate disability(List<Disability> disability) {
    this.disability = disability;
    return this;
  }

  public IndividualCreate addDisabilityItem(Disability disabilityItem) {
    if (this.disability == null) {
      this.disability = new ArrayList<Disability>();
    }
    this.disability.add(disabilityItem);
    return this;
  }

   /**
   * Get disability
   * @return disability
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<Disability> getDisability() {
    return disability;
  }

  public void setDisability(List<Disability> disability) {
    this.disability = disability;
  }

  public IndividualCreate individualIdentification(List<IndividualIdentification> individualIdentification) {
    this.individualIdentification = individualIdentification;
    return this;
  }

  public IndividualCreate addIndividualIdentificationItem(IndividualIdentification individualIdentificationItem) {
    if (this.individualIdentification == null) {
      this.individualIdentification = new ArrayList<IndividualIdentification>();
    }
    this.individualIdentification.add(individualIdentificationItem);
    return this;
  }

   /**
   * Get individualIdentification
   * @return individualIdentification
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<IndividualIdentification> getIndividualIdentification() {
    return individualIdentification;
  }

  public void setIndividualIdentification(List<IndividualIdentification> individualIdentification) {
    this.individualIdentification = individualIdentification;
  }

  public IndividualCreate languageAbility(List<LanguageAbility> languageAbility) {
    this.languageAbility = languageAbility;
    return this;
  }

  public IndividualCreate addLanguageAbilityItem(LanguageAbility languageAbilityItem) {
    if (this.languageAbility == null) {
      this.languageAbility = new ArrayList<LanguageAbility>();
    }
    this.languageAbility.add(languageAbilityItem);
    return this;
  }

   /**
   * Get languageAbility
   * @return languageAbility
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<LanguageAbility> getLanguageAbility() {
    return languageAbility;
  }

  public void setLanguageAbility(List<LanguageAbility> languageAbility) {
    this.languageAbility = languageAbility;
  }

  public IndividualCreate partyCharacteristic(List<Characteristic> partyCharacteristic) {
    this.partyCharacteristic = partyCharacteristic;
    return this;
  }

  public IndividualCreate addPartyCharacteristicItem(Characteristic partyCharacteristicItem) {
    if (this.partyCharacteristic == null) {
      this.partyCharacteristic = new ArrayList<Characteristic>();
    }
    this.partyCharacteristic.add(partyCharacteristicItem);
    return this;
  }

   /**
   * Get partyCharacteristic
   * @return partyCharacteristic
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<Characteristic> getPartyCharacteristic() {
    return partyCharacteristic;
  }

  public void setPartyCharacteristic(List<Characteristic> partyCharacteristic) {
    this.partyCharacteristic = partyCharacteristic;
  }

  public IndividualCreate relatedParty(List<RelatedParty> relatedParty) {
    this.relatedParty = relatedParty;
    return this;
  }

  public IndividualCreate addRelatedPartyItem(RelatedParty relatedPartyItem) {
    this.relatedParty.add(relatedPartyItem);
    return this;
  }

   /**
   * Get relatedParty
   * @return relatedParty
  **/
  @NotNull
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "")
  public List<RelatedParty> getRelatedParty() {
    return relatedParty;
  }

  public void setRelatedParty(List<RelatedParty> relatedParty) {
    this.relatedParty = relatedParty;
  }

  public IndividualCreate skill(List<Skill> skill) {
    this.skill = skill;
    return this;
  }

  public IndividualCreate addSkillItem(Skill skillItem) {
    if (this.skill == null) {
      this.skill = new ArrayList<Skill>();
    }
    this.skill.add(skillItem);
    return this;
  }

   /**
   * Get skill
   * @return skill
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<Skill> getSkill() {
    return skill;
  }

  public void setSkill(List<Skill> skill) {
    this.skill = skill;
  }

  public IndividualCreate status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public void setSource(String source) {
    this.source = source;
  }

  public String getSource(String source) {
    return source;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualCreate individualCreate = (IndividualCreate) o;
    return Objects.equals(this.id, individualCreate.id) &&
        Objects.equals(this.effectiveDate, individualCreate.effectiveDate) &&
        Objects.equals(this.birthDate, individualCreate.birthDate) &&
        Objects.equals(this.familyName, individualCreate.familyName) &&
        Objects.equals(this.familyNamePrefix, individualCreate.familyNamePrefix) &&
        Objects.equals(this.gender, individualCreate.gender) &&
        Objects.equals(this.givenName, individualCreate.givenName) &&
        Objects.equals(this.legalName, individualCreate.legalName) &&
        Objects.equals(this.maritalStatus, individualCreate.maritalStatus) &&
        Objects.equals(this.nationality, individualCreate.nationality) &&
        Objects.equals(this.preferredGivenName, individualCreate.preferredGivenName) &&
        Objects.equals(this.title, individualCreate.title) &&
        Objects.equals(this._case, individualCreate._case) &&
        Objects.equals(this.contactMedium, individualCreate.contactMedium) &&
        Objects.equals(this.disability, individualCreate.disability) &&
        Objects.equals(this.individualIdentification, individualCreate.individualIdentification) &&
        Objects.equals(this.languageAbility, individualCreate.languageAbility) &&
        Objects.equals(this.partyCharacteristic, individualCreate.partyCharacteristic) &&
        Objects.equals(this.relatedParty, individualCreate.relatedParty) &&
        Objects.equals(this.skill, individualCreate.skill) &&
        Objects.equals(this.status, individualCreate.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, effectiveDate, birthDate, familyName, familyNamePrefix, gender, givenName, legalName, maritalStatus, nationality, preferredGivenName, title, _case, contactMedium, disability, individualIdentification, languageAbility, partyCharacteristic, relatedParty, skill, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualCreate {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    effectiveDate: ").append(toIndentedString(effectiveDate)).append("\n");
    sb.append("    birthDate: ").append(toIndentedString(birthDate)).append("\n");
    sb.append("    familyName: ").append(toIndentedString(familyName)).append("\n");
    sb.append("    familyNamePrefix: ").append(toIndentedString(familyNamePrefix)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    givenName: ").append(toIndentedString(givenName)).append("\n");
    sb.append("    legalName: ").append(toIndentedString(legalName)).append("\n");
    sb.append("    maritalStatus: ").append(toIndentedString(maritalStatus)).append("\n");
    sb.append("    nationality: ").append(toIndentedString(nationality)).append("\n");
    sb.append("    preferredGivenName: ").append(toIndentedString(preferredGivenName)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    _case: ").append(toIndentedString(_case)).append("\n");
    sb.append("    contactMedium: ").append(toIndentedString(contactMedium)).append("\n");
    sb.append("    disability: ").append(toIndentedString(disability)).append("\n");
    sb.append("    individualIdentification: ").append(toIndentedString(individualIdentification)).append("\n");
    sb.append("    languageAbility: ").append(toIndentedString(languageAbility)).append("\n");
    sb.append("    partyCharacteristic: ").append(toIndentedString(partyCharacteristic)).append("\n");
    sb.append("    relatedParty: ").append(toIndentedString(relatedParty)).append("\n");
    sb.append("    skill: ").append(toIndentedString(skill)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    source: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
