/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Represents our registration of information used as proof of identity by an individual (passport, national identity card, drivers license, social security number, birth certificate)
 */
@Schema(description = "Represents our registration of information used as proof of identity by an individual (passport, national identity card, drivers license, social security number, birth certificate)")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class IndividualIdentification {
  @JsonProperty("identificationId")
  private String identificationId = null;

  @JsonProperty("identificationType")
  private String identificationType = null;

  public IndividualIdentification identificationId(String identificationId) {
    this.identificationId = identificationId;
    return this;
  }

   /**
   * DriversLicense-&gt;SV_MAPPING:Contact.DriverLicenseNum_X | Individual-&gt;SV_MAPPING:Contact.Password_X | Passport-&gt;SV_MAPPING:Contact.PassportNum_X | SocialSecurityNumber-&gt; SV_MAPPING:Contact.SocialSecurityNum_X | NationalId -&gt; SV_MAPPING:Contact.UI_National_Id_X
   * @return identificationId
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "DriversLicense->SV_MAPPING:Contact.DriverLicenseNum_X | Individual->SV_MAPPING:Contact.Password_X | Passport->SV_MAPPING:Contact.PassportNum_X | SocialSecurityNumber-> SV_MAPPING:Contact.SocialSecurityNum_X | NationalId -> SV_MAPPING:Contact.UI_National_Id_X")
  public String getIdentificationId() {
    return identificationId;
  }

  public void setIdentificationId(String identificationId) {
    this.identificationId = identificationId;
  }

  public IndividualIdentification identificationType(String identificationType) {
    this.identificationType = identificationType;
    return this;
  }

   /**
   * DriversLicense | Individual | Passport | SocialSecurityNumber | NationalId 
   * @return identificationType
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "DriversLicense | Individual | Passport | SocialSecurityNumber | NationalId ")
  public String getIdentificationType() {
    return identificationType;
  }

  public void setIdentificationType(String identificationType) {
    this.identificationType = identificationType;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IndividualIdentification individualIdentification = (IndividualIdentification) o;
    return Objects.equals(this.identificationId, individualIdentification.identificationId) &&
        Objects.equals(this.identificationType, individualIdentification.identificationType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(identificationId, identificationType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IndividualIdentification {\n");
    
    sb.append("    identificationId: ").append(toIndentedString(identificationId)).append("\n");
    sb.append("    identificationType: ").append(toIndentedString(identificationType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
