/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Ability of an individual to understand or converse in a language.
 */
@Schema(description = "Ability of an individual to understand or converse in a language.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class LanguageAbility {
  @JsonProperty("speakingProficiency")
  private String speakingProficiency = null;

  @JsonProperty("writingProficiency")
  private String writingProficiency = null;

  public LanguageAbility speakingProficiency(String speakingProficiency) {
    this.speakingProficiency = speakingProficiency;
    return this;
  }

   /**
   * Spoken Language RT, SV_MAPPING:Contact.SpokenLanguage_R
   * @return speakingProficiency
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Spoken Language RT, SV_MAPPING:Contact.SpokenLanguage_R")
  public String getSpeakingProficiency() {
    return speakingProficiency;
  }

  public void setSpeakingProficiency(String speakingProficiency) {
    this.speakingProficiency = speakingProficiency;
  }

  public LanguageAbility writingProficiency(String writingProficiency) {
    this.writingProficiency = writingProficiency;
    return this;
  }

   /**
   * Written Language RT, SV_MAPPING:Contact.WrittenLanguage_R
   * @return writingProficiency
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Written Language RT, SV_MAPPING:Contact.WrittenLanguage_R")
  public String getWritingProficiency() {
    return writingProficiency;
  }

  public void setWritingProficiency(String writingProficiency) {
    this.writingProficiency = writingProficiency;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LanguageAbility languageAbility = (LanguageAbility) o;
    return Objects.equals(this.speakingProficiency, languageAbility.speakingProficiency) &&
        Objects.equals(this.writingProficiency, languageAbility.writingProficiency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(speakingProficiency, writingProficiency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class LanguageAbility {\n");
    
    sb.append("    speakingProficiency: ").append(toIndentedString(speakingProficiency)).append("\n");
    sb.append("    writingProficiency: ").append(toIndentedString(writingProficiency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
