/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Describes the contact medium characteristics that could be used to contact a party. Its value depends on the specified medium type
 */
@Schema(description = "Describes the contact medium characteristics that could be used to contact a party. Its value depends on the specified medium type")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class MediumCharacteristic {
  @JsonProperty("city")
  private String city = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("emailAddress")
  private String emailAddress = null;

  @JsonProperty("verified")
  private String verified = null;

  @JsonProperty("secondaryEmailAddress")
  private List<String> secondaryEmailAddress = null;

  @JsonProperty("secondaryEmailAddressWithVerification")
  private List<AdditionalEmailAddressWithVerification> secondaryEmailAddressWithVerification = null;

  @JsonProperty("faxNumber")
  private String faxNumber = null;

  @JsonProperty("phoneNumber")
  private String phoneNumber = null;

  @JsonProperty("postCode")
  private String postCode = null;

  @JsonProperty("stateOrProvince")
  private String stateOrProvince = null;

  @JsonProperty("street1")
  private String street1 = null;

  @JsonProperty("street2")
  private String street2 = null;

  @JsonProperty("suburb")
  private String suburb = null;

  @JsonProperty("addressLine1")
  private String addressLine1 = null;

  @JsonProperty("geocode")
  private String geocode = null;

  @JsonProperty("subDoorNumber")
  private String subDoorNumber = null;

  @JsonProperty("genericAddress")
  private String genericAddress = null;

  public MediumCharacteristic city(String city) {
    this.city = city;
    return this;
  }

   /**
   * HomeAddress -&gt;SV_MAPPING:Contact.City_R | WorkAddress -&gt; SV_MAPPING:Contact.WorkCity_R | PostalAddress -&gt; SV_MAPPING:Contact.PostalCity_R
   * @return city
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress ->SV_MAPPING:Contact.City_R | WorkAddress -> SV_MAPPING:Contact.WorkCity_R | PostalAddress -> SV_MAPPING:Contact.PostalCity_R")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public MediumCharacteristic country(String country) {
    this.country = country;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.Country_R |  WorkAddress -&gt; SV_MAPPING:Contact.WorkCountry_R | PostalAddress -&gt; SV_MAPPING:Contact.PostalCountry_R
   * @return country
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.Country_R |  WorkAddress -> SV_MAPPING:Contact.WorkCountry_R | PostalAddress -> SV_MAPPING:Contact.PostalCountry_R")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public MediumCharacteristic emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

   /**
   * DefaultEmailAddress -&gt; SV_MAPPING:Contact.EmailAddress_X
   * @return emailAddress
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "DefaultEmailAddress -> SV_MAPPING:Contact.EmailAddress_X")
  public String getEmailAddress() {
    return emailAddress;
  }

  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public MediumCharacteristic verified(String verified) {
    this.verified = verified;
    return this;
  }

   /**
   * Specifies Primary Email is verified or not. DefaultEmailAddress -&gt; SV_MAPPING:ContactComms.Verified_B
   * @return verified
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Specifies Primary Email is verified or not. DefaultEmailAddress -> SV_MAPPING:ContactComms.Verified_B")
  public String getVerified() {
    return verified;
  }

  public void setVerified(String verified) {
    this.verified = verified;
  }

  public MediumCharacteristic secondaryEmailAddress(List<String> secondaryEmailAddress) {
    this.secondaryEmailAddress = secondaryEmailAddress;
    return this;
  }

  public MediumCharacteristic addSecondaryEmailAddressItem(String secondaryEmailAddressItem) {
    if (this.secondaryEmailAddress == null) {
      this.secondaryEmailAddress = new ArrayList<String>();
    }
    this.secondaryEmailAddress.add(secondaryEmailAddressItem);
    return this;
  }

   /**
   * This will be used for mediumType SecondaryEmailAddress
   * @return secondaryEmailAddress
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "This will be used for mediumType SecondaryEmailAddress")
  public List<String> getSecondaryEmailAddress() {
    return secondaryEmailAddress;
  }

  public void setSecondaryEmailAddress(List<String> secondaryEmailAddress) {
    this.secondaryEmailAddress = secondaryEmailAddress;
  }

  public MediumCharacteristic secondaryEmailAddressWithVerification(List<AdditionalEmailAddressWithVerification> secondaryEmailAddressWithVerification) {
    this.secondaryEmailAddressWithVerification = secondaryEmailAddressWithVerification;
    return this;
  }

  public MediumCharacteristic addSecondaryEmailAddressWithVerificationItem(AdditionalEmailAddressWithVerification secondaryEmailAddressWithVerificationItem) {
    if (this.secondaryEmailAddressWithVerification == null) {
      this.secondaryEmailAddressWithVerification = new ArrayList<AdditionalEmailAddressWithVerification>();
    }
    this.secondaryEmailAddressWithVerification.add(secondaryEmailAddressWithVerificationItem);
    return this;
  }

   /**
   * This will be used for mediumType VerifiedSecondaryEmailAddress
   * @return secondaryEmailAddressWithVerification
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "This will be used for mediumType VerifiedSecondaryEmailAddress")
  public List<AdditionalEmailAddressWithVerification> getSecondaryEmailAddressWithVerification() {
    return secondaryEmailAddressWithVerification;
  }

  public void setSecondaryEmailAddressWithVerification(List<AdditionalEmailAddressWithVerification> secondaryEmailAddressWithVerification) {
    this.secondaryEmailAddressWithVerification = secondaryEmailAddressWithVerification;
  }

  public MediumCharacteristic faxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
    return this;
  }

   /**
   * FaxNumber -&gt; SV_MAPPING:Contact.FaxPhone_X
   * @return faxNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "FaxNumber -> SV_MAPPING:Contact.FaxPhone_X")
  public String getFaxNumber() {
    return faxNumber;
  }

  public void setFaxNumber(String faxNumber) {
    this.faxNumber = faxNumber;
  }

  public MediumCharacteristic phoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
    return this;
  }

   /**
   * HomeNumber -&gt; SV_MAPPING:Contact.HomePhone_X | WorkNumber -&gt; SV_MAPPING:Contact.WorkPhone_X | MobileNumber -&gt; SV_MAPPING:Contact.MobilePhone_X
   * @return phoneNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeNumber -> SV_MAPPING:Contact.HomePhone_X | WorkNumber -> SV_MAPPING:Contact.WorkPhone_X | MobileNumber -> SV_MAPPING:Contact.MobilePhone_X")
  public String getPhoneNumber() {
    return phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public MediumCharacteristic postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomePostCode_X | WorkAddress -&gt; SV_MAPPING:Contact.WorkPostCode_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalPostCode_X
   * @return postCode
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomePostCode_X | WorkAddress -> SV_MAPPING:Contact.WorkPostCode_X | PostalAddress -> SV_MAPPING:Contact.PostalPostCode_X")
  public String getPostCode() {
    return postCode;
  }

  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }

  public MediumCharacteristic stateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.District_R | WorkAddress -&gt; SV_MAPPING:Contact.WorkDistrict_R | PostalAddress -&gt; SV_MAPPING:Contact.PostalDistrict_R
   * @return stateOrProvince
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.District_R | WorkAddress -> SV_MAPPING:Contact.WorkDistrict_R | PostalAddress -> SV_MAPPING:Contact.PostalDistrict_R")
  public String getStateOrProvince() {
    return stateOrProvince;
  }

  public void setStateOrProvince(String stateOrProvince) {
    this.stateOrProvince = stateOrProvince;
  }

  public MediumCharacteristic street1(String street1) {
    this.street1 = street1;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomeLine1_X | WorkAddress -&gt; SV_MAPPING:Contact.WorkLine1_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalLine1_X
   * @return street1
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomeLine1_X | WorkAddress -> SV_MAPPING:Contact.WorkLine1_X | PostalAddress -> SV_MAPPING:Contact.PostalLine1_X")
  public String getStreet1() {
    return street1;
  }

  public void setStreet1(String street1) {
    this.street1 = street1;
  }

  public MediumCharacteristic street2(String street2) {
    this.street2 = street2;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomeLine2_X | WorkAddress -&gt; SV_MAPPING:Contact.WorkLine2_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalLine2_X
   * @return street2
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomeLine2_X | WorkAddress -> SV_MAPPING:Contact.WorkLine2_X | PostalAddress -> SV_MAPPING:Contact.PostalLine2_X")
  public String getStreet2() {
    return street2;
  }

  public void setStreet2(String street2) {
    this.street2 = street2;
  }

  public MediumCharacteristic suburb(String suburb) {
    this.suburb = suburb;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.SubDistrict_R | WorkAddress -&gt; SV_MAPPING:Contact.WorkSubDistrict_R | PostalAddress -&gt; SV_MAPPING:Contact.PostalSubDistrict_R
   * @return suburb
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.SubDistrict_R | WorkAddress -> SV_MAPPING:Contact.WorkSubDistrict_R | PostalAddress -> SV_MAPPING:Contact.PostalSubDistrict_R")
  public String getSuburb() {
    return suburb;
  }

  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }

  public MediumCharacteristic addressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomeLine7_X | WorkAddress -&gt; SV_MAPPING:Contact.WorkLine7_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalLine7_X
   * @return addressLine1
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomeLine7_X | WorkAddress -> SV_MAPPING:Contact.WorkLine7_X | PostalAddress -> SV_MAPPING:Contact.PostalLine7_X")
  public String getAddressLine1() {
    return addressLine1;
  }

  public void setAddressLine1(String addressLine1) {
    this.addressLine1 = addressLine1;
  }

  public MediumCharacteristic geocode(String geocode) {
    this.geocode = geocode;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomeGeocode_X | WorkAddress -&gt; SV_MAPPING:Contact.WorkGeocode_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalGeocode_X
   * @return geocode
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomeGeocode_X | WorkAddress -> SV_MAPPING:Contact.WorkGeocode_X | PostalAddress -> SV_MAPPING:Contact.PostalGeocode_X")
  public String getGeocode() {
    return geocode;
  }

  public void setGeocode(String geocode) {
    this.geocode = geocode;
  }

  public MediumCharacteristic subDoorNumber(String subDoorNumber) {
    this.subDoorNumber = subDoorNumber;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomeSubDoorNumber_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalSubDoorNumber_X
   * @return subDoorNumber
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomeSubDoorNumber_X | PostalAddress -> SV_MAPPING:Contact.PostalSubDoorNumber_X")
  public String getSubDoorNumber() {
    return subDoorNumber;
  }

  public void setSubDoorNumber(String subDoorNumber) {
    this.subDoorNumber = subDoorNumber;
  }

  public MediumCharacteristic genericAddress(String genericAddress) {
    this.genericAddress = genericAddress;
    return this;
  }

   /**
   * HomeAddress -&gt; SV_MAPPING:Contact.HomeGenericAddress_X | PostalAddress -&gt; SV_MAPPING:Contact.PostalGenericAddress_X
   * @return genericAddress
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "HomeAddress -> SV_MAPPING:Contact.HomeGenericAddress_X | PostalAddress -> SV_MAPPING:Contact.PostalGenericAddress_X")
  public String getGenericAddress() {
    return genericAddress;
  }

  public void setGenericAddress(String genericAddress) {
    this.genericAddress = genericAddress;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MediumCharacteristic mediumCharacteristic = (MediumCharacteristic) o;
    return Objects.equals(this.city, mediumCharacteristic.city) &&
        Objects.equals(this.country, mediumCharacteristic.country) &&
        Objects.equals(this.emailAddress, mediumCharacteristic.emailAddress) &&
        Objects.equals(this.verified, mediumCharacteristic.verified) &&
        Objects.equals(this.secondaryEmailAddress, mediumCharacteristic.secondaryEmailAddress) &&
        Objects.equals(this.secondaryEmailAddressWithVerification, mediumCharacteristic.secondaryEmailAddressWithVerification) &&
        Objects.equals(this.faxNumber, mediumCharacteristic.faxNumber) &&
        Objects.equals(this.phoneNumber, mediumCharacteristic.phoneNumber) &&
        Objects.equals(this.postCode, mediumCharacteristic.postCode) &&
        Objects.equals(this.stateOrProvince, mediumCharacteristic.stateOrProvince) &&
        Objects.equals(this.street1, mediumCharacteristic.street1) &&
        Objects.equals(this.street2, mediumCharacteristic.street2) &&
        Objects.equals(this.suburb, mediumCharacteristic.suburb) &&
        Objects.equals(this.addressLine1, mediumCharacteristic.addressLine1) &&
        Objects.equals(this.geocode, mediumCharacteristic.geocode) &&
        Objects.equals(this.subDoorNumber, mediumCharacteristic.subDoorNumber) &&
        Objects.equals(this.genericAddress, mediumCharacteristic.genericAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(city, country, emailAddress, verified, secondaryEmailAddress, secondaryEmailAddressWithVerification, faxNumber, phoneNumber, postCode, stateOrProvince, street1, street2, suburb, addressLine1, geocode, subDoorNumber, genericAddress);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MediumCharacteristic {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    secondaryEmailAddress: ").append(toIndentedString(secondaryEmailAddress)).append("\n");
    sb.append("    secondaryEmailAddressWithVerification: ").append(toIndentedString(secondaryEmailAddressWithVerification)).append("\n");
    sb.append("    faxNumber: ").append(toIndentedString(faxNumber)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    stateOrProvince: ").append(toIndentedString(stateOrProvince)).append("\n");
    sb.append("    street1: ").append(toIndentedString(street1)).append("\n");
    sb.append("    street2: ").append(toIndentedString(street2)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    addressLine1: ").append(toIndentedString(addressLine1)).append("\n");
    sb.append("    geocode: ").append(toIndentedString(geocode)).append("\n");
    sb.append("    subDoorNumber: ").append(toIndentedString(subDoorNumber)).append("\n");
    sb.append("    genericAddress: ").append(toIndentedString(genericAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
