/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * Related Entity reference.A related party defines party or party role linked to a specific entity.
 */
@Schema(description = "Related Entity reference.A related party defines party or party role linked to a specific entity.")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class RelatedParty {
  @JsonProperty("id")
  private String id = null;

  @JsonProperty("href")
  private String href = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("@referredType")
  private String _atReferredType = null;

  @JsonProperty("contactMedium")
  private List<ContactMedium> contactMedium = null;

  @JsonProperty("partyCharacteristic")
  private List<Characteristic> partyCharacteristic = null;

  public RelatedParty id(String id) {
    this.id = id;
    return this;
  }

   /**
   * It will be unique Id of the entity mentioned. For personType SV_MAPPING:Contact_Type.XSID | For customer SV_MAPPING:CustAcct_Contact.Cust_Acct.ObjectKey
   * @return id
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "It will be unique Id of the entity mentioned. For personType SV_MAPPING:Contact_Type.XSID | For customer SV_MAPPING:CustAcct_Contact.Cust_Acct.ObjectKey")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public RelatedParty href(String href) {
    this.href = href;
    return this;
  }

   /**
   * Reference of the related entity.customer - &lt;http://&lt;PEREST_HOSTNAME&gt;:&lt;PEREST_PORT&gt;/&lt;customer PEREST URL&gt;/&lt;SV_MAPPING:Cust_Acct.ObjectKey&gt;
   * @return href
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Reference of the related entity.customer - <http://<PEREST_HOSTNAME>:<PEREST_PORT>/<customer PEREST URL>/<SV_MAPPING:Cust_Acct.ObjectKey>")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public RelatedParty name(String name) {
    this.name = name;
    return this;
  }

   /**
   * For personType SV_MAPPING:Contact.Type | For customer SV_MAPPING:Cust_Acct.CustAcctName_X
   * @return name
  **/
  @NotNull
  @Schema(requiredMode = Schema.RequiredMode.REQUIRED, description = "For personType SV_MAPPING:Contact.Type | For customer SV_MAPPING:Cust_Acct.CustAcctName_X")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public RelatedParty _atReferredType(String _atReferredType) {
    this._atReferredType = _atReferredType;
    return this;
  }

   /**
   * The actual type of the target instance when needed for disambiguation. Valid Values: personType | customer
   * @return _atReferredType
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "The actual type of the target instance when needed for disambiguation. Valid Values: personType | customer")
  public String getAtReferredType() {
    return _atReferredType;
  }

  public void setAtReferredType(String _atReferredType) {
    this._atReferredType = _atReferredType;
  }

  public RelatedParty contactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
    return this;
  }

  public RelatedParty addContactMediumItem(ContactMedium contactMediumItem) {
    if (this.contactMedium == null) {
      this.contactMedium = new ArrayList<ContactMedium>();
    }
    this.contactMedium.add(contactMediumItem);
    return this;
  }

   /**
   * Get contactMedium
   * @return contactMedium
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<ContactMedium> getContactMedium() {
    return contactMedium;
  }

  public void setContactMedium(List<ContactMedium> contactMedium) {
    this.contactMedium = contactMedium;
  }

  public RelatedParty partyCharacteristic(List<Characteristic> partyCharacteristic) {
    this.partyCharacteristic = partyCharacteristic;
    return this;
  }

  public RelatedParty addPartyCharacteristicItem(Characteristic partyCharacteristicItem) {
    if (this.partyCharacteristic == null) {
      this.partyCharacteristic = new ArrayList<Characteristic>();
    }
    this.partyCharacteristic.add(partyCharacteristicItem);
    return this;
  }

   /**
   * Get partyCharacteristic
   * @return partyCharacteristic
  **/
  @Valid
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "")
  public List<Characteristic> getPartyCharacteristic() {
    return partyCharacteristic;
  }

  public void setPartyCharacteristic(List<Characteristic> partyCharacteristic) {
    this.partyCharacteristic = partyCharacteristic;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RelatedParty relatedParty = (RelatedParty) o;
    return Objects.equals(this.id, relatedParty.id) &&
        Objects.equals(this.href, relatedParty.href) &&
        Objects.equals(this.name, relatedParty.name) &&
        Objects.equals(this._atReferredType, relatedParty._atReferredType) &&
        Objects.equals(this.contactMedium, relatedParty.contactMedium) &&
        Objects.equals(this.partyCharacteristic, relatedParty.partyCharacteristic);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, name, _atReferredType, contactMedium, partyCharacteristic);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RelatedParty {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    _atReferredType: ").append(toIndentedString(_atReferredType)).append("\n");
    sb.append("    contactMedium: ").append(toIndentedString(contactMedium)).append("\n");
    sb.append("    partyCharacteristic: ").append(toIndentedString(partyCharacteristic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
