/*
 * Party Management
 * This is Swagger specification for the TMF Party Management. 
 *
 * OpenAPI spec version: $Revision: 1.22 $
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.airtel.africa.integration.accountmanagement.model.party;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.quarkus.runtime.annotations.RegisterForReflection;
import io.swagger.v3.oas.annotations.media.Schema;

import java.util.Objects;
/**
 * Skills evaluated for an individual with a level and possibly with a limited validity when an obsolescence is defined(Ex: the first - aid certificate first level is limited to one year and an update training is required each year to keep the level).
 */
@Schema(description = "Skills evaluated for an individual with a level and possibly with a limited validity when an obsolescence is defined(Ex: the first - aid certificate first level is limited to one year and an update training is required each year to keep the level).")
@jakarta.annotation.Generated(value = "org.apache.camel.quarkus.component.rest.openapi.deployment.QuarkusCodegen", date = "2025-07-31T12:31:11.469290+05:30[Asia/Kolkata]")
@JsonInclude(JsonInclude.Include.NON_NULL)
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)

public class Skill {
  @JsonProperty("skillName")
  private String skillName = null;

  public Skill skillName(String skillName) {
    this.skillName = skillName;
    return this;
  }

   /**
   * Profession RT, SV_MAPPING:Contact.Profession_R
   * @return skillName
  **/
  @Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, description = "Profession RT, SV_MAPPING:Contact.Profession_R")
  public String getSkillName() {
    return skillName;
  }

  public void setSkillName(String skillName) {
    this.skillName = skillName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Skill skill = (Skill) o;
    return Objects.equals(this.skillName, skill.skillName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(skillName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Skill {\n");
    
    sb.append("    skillName: ").append(toIndentedString(skillName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
